// Generated by CoffeeScript 1.7.1
(function() {
  var bytes2any;

  angular.module("pony.bytes", ["ng"]);

  bytes2any = function(bytes, precision, offset) {
    var number, units;
    if (isNaN(parseFloat(bytes)) || !isFinite(bytes)) {
      return "-";
    }
    if (typeof precision === "undefined") {
      precision = 1;
    }
    units = ["bytes", "KiB", "MiB", "GiB", "TiB", "PiB", "EiB", "ZiB", "YiB"];
    number = Math.floor(Math.log(bytes) / Math.log(1024));
    return (bytes / Math.pow(1024, Math.floor(number))).toFixed(precision) + " " + units[number + offset];
  };

  angular.module("pony.bytes").filter("bytes", function($parse, $timeout) {
    return function(bytes, precision) {
      return bytes2any(bytes, precision);
    };
  });

  angular.module("pony.bytes").filter("megabytes", function($parse, $timeout) {
    return function(megabytes, precision) {
      return bytes2any(megabytes, precision, 2);
    };
  });

}).call(this);
