// Generated by CoffeeScript 1.7.1
(function() {
  var InstanceDetailCtrl, InstanceListCtrl, InstanceWizardCtrl, module;

  module = angular.module('tenantInstance', ['rainbowServices']);

  module.config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/:tenant/instance', {
        templateUrl: 'tenant/instance/instance-list.tpl.html',
        controller: 'InstanceListCtrl'
      });
      $routeProvider.when('/:tenant/instance/create', {
        templateUrl: 'tenant/instance/instance-wizard.tpl.html',
        controller: 'InstanceWizardCtrl'
      });
      return $routeProvider.when('/:tenant/instance/:instance', {
        templateUrl: 'tenant/instance/instance-detail.tpl.html',
        controller: 'InstanceDetailCtrl'
      });
    }
  ]);

  module.controller('InstanceListCtrl', InstanceListCtrl = (function() {
    InstanceListCtrl.inject = ['$scope', '$routeParams', 'TenantInstance', 'dataContainer'];

    function InstanceListCtrl($scope, $routeParams, TenantInstance, dataContainer, $modal) {
      var list;
      list = TenantInstance.list({
        tenant: $routeParams.tenant
      });
      list.$promise.then(function(i) {
        $scope.instances = i;
        return dataContainer.registerEntity('instance', $scope.instances);
      });
    }

    return InstanceListCtrl;

  })());

  module.controller('InstanceDetailCtrl', InstanceDetailCtrl = (function() {
    InstanceDetailCtrl.$inject = ['$scope', '$routeParams', '$modal', 'TenantInstance', 'TenantVolume', 'TenantInstanceVdisk', 'TenantInstanceVnic', 'TenantInstanceVnicAddress', 'StoragePool', 'dataContainer'];

    function InstanceDetailCtrl($scope, $routeParams, $modal, TenantInstance, TenantVolume, TenantInstanceVdisk, TenantInstanceVnic, TenantInstanceVnicAddress, StoragePool, dataContainer) {
      $scope.instanceEditModal = $modal({
        keyboard: true,
        scope: $scope,
        template: 'tenant/instance/instance-edit-modal.tpl.html',
        show: false
      });
      $scope.vnicListModal = $modal({
        keyboard: true,
        scope: $scope,
        template: 'tenant/instance/vnic-list-modal.tpl.html',
        show: false
      });
      $scope.vdiskListModal = $modal({
        keyboard: true,
        scope: $scope,
        template: 'tenant/instance/vdisk-list-modal.tpl.html',
        show: false
      });
      $scope.vdiskListClose = function() {
        return $scope.vdiskListModal.hide();
      };
      $scope.vdiskListOpen = function() {
        return $scope.vdiskListModal.show();
      };
      $scope.instance = TenantInstance.get({
        tenant: $routeParams.tenant,
        instance: $routeParams.instance
      });
      TenantInstanceVdisk.list({
        'tenant': $routeParams.tenant,
        'instance': $routeParams.instance
      }).$promise.then(function(vdisks) {
        $scope.vdisks = vdisks;
        return dataContainer.registerEntity('vdisk', $scope.vdisks);
      });
      TenantVolume.list({
        'tenant': $routeParams.tenant
      }).$promise.then(function(volumes) {
        $scope.volumes = volumes;
        dataContainer.registerEntity('volume', $scope.volumes);
        return $scope.$watch('volumes', function(value) {
          var volume, _i, _len, _results;
          $scope.volumeDict = {};
          $scope.filteredVolumes = [];
          _results = [];
          for (_i = 0, _len = value.length; _i < _len; _i++) {
            volume = value[_i];
            $scope.volumeDict[volume.desired.uuid] = volume;
            if (!volume.desired.image) {
              _results.push($scope.filteredVolumes.push(volume));
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        });
      });
      TenantInstanceVnic.list({
        tenant: $routeParams.tenant,
        instance: $routeParams.instance
      }).$promise.then(function(vnics) {
        return $scope.vnics = vnics;
      });
      $scope.vnicIps = TenantInstanceVnic.get({
        tenant: $routeParams.tenant,
        instance: $routeParams.instance,
        vnic: $routeParams.vnic
      });
      $scope.volumeFilter = function(actual, expected) {
        var nameTest, regex, sizeTest;
        regex = new RegExp("^" + expected, 'i');
        nameTest = regex.test($scope.volumeDict[actual].desired.name);
        sizeTest = regex.test($scope.volumeDict[actual].desired.size);
        return nameTest || sizeTest;
      };
      $scope.createVdisk = function(volume) {
        var item, max, newVdisk, _i, _len, _ref;
        max = 0;
        _ref = $scope.vdisks;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          if (item.desired.index > max) {
            max = item.desired.index;
          }
        }
        newVdisk = new TenantInstanceVdisk();
        newVdisk.desired = {
          'volume': volume.desired.uuid,
          'index': max + 1,
          'name': volume.desired.name
        };
        return newVdisk.$save({
          'tenant': $routeParams.tenant,
          'instance': $routeParams.instance
        }, function(response) {
          return $scope.vdiskListClose();
        });
      };
      $scope.deleteVdisk = function(vdisk) {
        var params;
        vdisk = JSON.parse(vdisk);
        params = {
          'tenant': $routeParams.tenant,
          'vdisk': vdisk.desired.uuid,
          'instance': vdisk.desired.instance
        };
        return TenantInstanceVdisk["delete"](params, function() {
          return $scope.message("Vdisk deleted", 'success');
        });
      };
      $scope.deleteSelectedVdisks = function(items) {
        var item, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = items.length; _i < _len; _i++) {
          item = items[_i];
          _results.push($scope.deleteVdisk(item));
        }
        return _results;
      };
    }

    return InstanceDetailCtrl;

  })());

  module.controller('InstanceWizardCtrl', InstanceWizardCtrl = (function() {
    InstanceWizardCtrl.$inject = ['$scope', '$routeParams', 'TenantInstance', 'TenantSwitchNetwork', 'TenantInstanceVdisk', 'TenantInstanceVnic', 'TenantSwitch', 'TenantInstanceVnicAddress', 'TenantVolume', 'StoragePool', 'CpuProfile', 'TenantAffinityGroup', 'dataContainer'];

    function InstanceWizardCtrl($scope, $routeParams, TenantInstance, TenantSwitchNetwork, TenantInstanceVdisk, TenantInstanceVnic, TenantSwitch, TenantInstanceVnicAddress, TenantVolume, StoragePool, CpuProfile, TenantAffinityGroup, dataContainer) {
      $scope.instance = {
        'selectedVolumes': [],
        'vdisks': [],
        'vnics': []
      };
      CpuProfile.list().$promise.then(function(cp) {
        $scope.cpu_profiles = cp;
        return dataContainer.registerEntity('cpu_profile', $scope.cpu_profiles);
      });
      TenantSwitch.list({
        tenant: $routeParams.tenant
      }).$promise.then(function(ts) {
        $scope.switches = ts;
        return dataContainer.registerEntity('switch', $scope.switches);
      });
      TenantVolume.list({
        'tenant': $routeParams.tenant
      }).$promise.then(function(VolumeList) {
        $scope.volumes = VolumeList;
        dataContainer.registerEntity('volume', $scope.volumes);
        return $scope.$watch('volumes', function(value) {
          return $scope.filteredVolumes = $scope.volumes.filter(function(item) {
            if (!item.desired.image) {
              return item;
            }
          });
        }, true);
      });
      TenantAffinityGroup.list({
        tenant: $routeParams.tenant
      }).$promise.then(function(ag) {
        $scope.affinity_groups = ag;
        return dataContainer.registerEntity('affinity_group', $scope.affinity_groups);
      });
      $scope.removeVnic = function(vnic) {
        return $scope.instance['vnics'] = $scope.instance['vnics'].filter(function(item) {
          return item.$$hashKey !== vnic.$$hashKey;
        });
      };
      $scope.addVnic = function() {
        var c;
        c = $scope.instance.vnics.push({
          'switch': null,
          'network': null,
          'addresses': []
        });
        $scope.$watch('instance.vnics[' + (c - 1) + '].switch', function(value) {
          return $scope.renewNetworks(value, c - 1);
        });
        return $scope.$watch('instance.vnics[' + (c - 1) + '].network', function(value) {
          return $scope.renewAddresses(value, c - 1);
        });
      };
      $scope.addVnic();
      $scope.finishedWizard = function() {
        return console.log("Dokonceno!");
      };
      $scope.renewAddresses = function(networkUUID, index) {
        var address, _i, _len, _ref;
        _ref = $scope.instance.vnics[index].addresses;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          address = _ref[_i];
          address.desired.network = networkUUID;
        }
        if ($scope.instance.vnics[index].addresses.length === 0) {
          return $scope.addAddress(networkUUID, $scope.instance.vnics[index]);
        }
      };
      $scope.addAddress = function(networkUUID, vnic) {
        var k;
        k = jQuery.inArray(vnic, $scope.instance.vnics);
        return $scope.instance.vnics[k].addresses.push({
          'desired': {
            'ip': '',
            'ptr': '',
            'network': networkUUID
          }
        });
      };
      $scope.removeAddress = function(address, vnic) {
        var k;
        k = jQuery.inArray(vnic, $scope.instance.vnics);
        return $scope.instance.vnics[k].addresses = $scope.instance.vnics[k].addresses.filter(function(item) {
          return item.$$hashKey !== address.$$hashKey;
        });
      };
      $scope.renewNetworks = function(switchUUID, index) {
        return TenantSwitchNetwork.list({
          tenant: $routeParams.tenant,
          "switch": switchUUID
        }).$promise.then(function(networks) {
          $scope.instance.vnics[index].networks = networks;
          return $scope.renewAddresses('', index);
        });
      };
      $scope.assignVolume = function(volume) {
        volume.selected = true;
        return $scope.instance['vdisks'].push({
          'desired': {
            'volume': volume.desired.uuid,
            'instance': '%instance_uuid%',
            'index': $scope.instance['vdisks'].length + 1
          },
          'volume': volume
        });
      };
      $scope.unassignVolume = function(volume) {
        var item, _i, _len, _ref;
        _ref = $scope.volumes;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          if (volume.desired.uuid === item.desired.uuid) {
            item.selected = false;
          }
        }
        return $scope.instance['vdisks'] = $scope.instance['vdisks'].filter(function(item) {
          return item.volume.desired.uuid !== volume.desired.uuid;
        });
      };
    }

    return InstanceWizardCtrl;

  })());

}).call(this);
