// Generated by CoffeeScript 1.7.1
(function() {
  var InstanceDetailCtrl, InstanceListCtrl, InstanceWizardCtrl, module;

  module = angular.module('tenantInstance', ['rainbowServices']);

  module.config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/:tenant/instance', {
        templateUrl: 'tenant/instance/instance-list.tpl.html',
        controller: 'InstanceListCtrl'
      });
      $routeProvider.when('/:tenant/instance/create', {
        templateUrl: 'tenant/instance/instance-wizard.tpl.html',
        controller: 'InstanceWizardCtrl'
      });
      return $routeProvider.when('/:tenant/instance/:instance', {
        templateUrl: 'tenant/instance/instance-detail.tpl.html',
        controller: 'InstanceDetailCtrl'
      });
    }
  ]);

  module.controller('InstanceListCtrl', InstanceListCtrl = (function() {
    InstanceListCtrl.inject = ['$scope', '$routeParams', 'TenantInstance', 'dataContainer'];

    function InstanceListCtrl($scope, $routeParams, TenantInstance, dataContainer, $modal) {
      var list;
      list = TenantInstance.list({
        tenant: $routeParams.tenant
      });
      list.$promise.then(function(i) {
        $scope.instances = i;
        return dataContainer.registerEntity('instance', $scope.instances);
      });
    }

    return InstanceListCtrl;

  })());

  module.controller('InstanceDetailCtrl', InstanceDetailCtrl = (function() {
    InstanceDetailCtrl.$inject = ['$scope', '$routeParams', 'TenantInstance', 'TenantInstanceVdisk', 'TenantInstanceVnic', 'TenantInstanceVnicAddress', 'StoragePool'];

    function InstanceDetailCtrl($scope, $routeParams, TenantInstance, TenantInstanceVdisk, TenantInstanceVnic, TenantInstanceVnicAddress, StoragePool) {
      $scope.instance = TenantInstance.get({
        tenant: $routeParams.tenant,
        instance: $routeParams.instance
      });
      $scope.vdisks = TenantInstanceVdisk.get({
        tenant: $routeParams.tenant,
        instance: $routeParams.instance
      });
      $scope.vnics = TenantInstanceVnic.get({
        tenant: $routeParams.tenant,
        instance: $routeParams.instance
      });
      $scope.vnicIps = TenantInstanceVnic.get({
        tenant: $routeParams.tenant,
        instance: $routeParams.instance,
        vnic: $routeParams.vnic
      });
    }

    return InstanceDetailCtrl;

  })());

  module.controller('InstanceWizardCtrl', InstanceWizardCtrl = (function() {
    InstanceWizardCtrl.$inject = ['$scope', '$routeParams', 'TenantInstance', 'TenantSwitchNetwork', 'TenantInstanceVdisk', 'TenantInstanceVnic', 'TenantSwitch', 'TenantInstanceVnicAddress', 'TenantVolume', 'StoragePool', 'CpuProfile', 'TenantAffinityGroup'];

    function InstanceWizardCtrl($scope, $routeParams, TenantInstance, TenantSwitchNetwork, TenantInstanceVdisk, TenantInstanceVnic, TenantSwitch, TenantInstanceVnicAddress, TenantVolume, StoragePool, CpuProfile, TenantAffinityGroup) {
      $scope.instance = {
        'selectedVolumes': [],
        'vdisks': [],
        'vnics': []
      };
      $scope.cpu_profiles = CpuProfile.list();
      $scope.switches = TenantSwitch.list({
        tenant: $routeParams.tenant
      });
      TenantVolume.list({
        tenant: $routeParams.tenant
      }).$promise.then(function(volumes) {
        return $scope.volumes = volumes.filter(function(item) {
          return 'image' in item.desired;
        });
      });
      $scope.affinity_groups = TenantAffinityGroup.list({
        tenant: $routeParams.tenant
      });
      $scope.removeVnic = function(vnic) {
        return $scope.instance['vnics'] = $scope.instance['vnics'].filter(function(item) {
          return item.$$hashKey !== vnic.$$hashKey;
        });
      };
      $scope.addVnic = function() {
        var c;
        c = $scope.instance.vnics.push({
          'switch': null,
          'network': null,
          'addresses': []
        });
        $scope.$watch('instance.vnics[' + (c - 1) + '].switch', function(value) {
          return $scope.renewNetworks(value, c - 1);
        });
        return $scope.$watch('instance.vnics[' + (c - 1) + '].network', function(value) {
          return $scope.renewAddresses(value, c - 1);
        });
      };
      $scope.addVnic();
      $scope.finishedWizard = function() {
        return console.log("Dokonceno!");
      };
      $scope.renewAddresses = function(networkUUID, index) {
        var address, _i, _len, _ref;
        _ref = $scope.instance.vnics[index].addresses;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          address = _ref[_i];
          address.desired.network = networkUUID;
        }
        if ($scope.instance.vnics[index].addresses.length === 0) {
          return $scope.addAddress(networkUUID, $scope.instance.vnics[index]);
        }
      };
      $scope.addAddress = function(networkUUID, vnic) {
        var k;
        k = jQuery.inArray(vnic, $scope.instance.vnics);
        return $scope.instance.vnics[k].addresses.push({
          'desired': {
            'ip': '',
            'ptr': '',
            'network': networkUUID
          }
        });
      };
      $scope.removeAddress = function(address, vnic) {
        var k;
        k = jQuery.inArray(vnic, $scope.instance.vnics);
        return $scope.instance.vnics[k].addresses = $scope.instance.vnics[k].addresses.filter(function(item) {
          return item.$$hashKey !== address.$$hashKey;
        });
      };
      $scope.renewNetworks = function(switchUUID, index) {
        return TenantSwitchNetwork.list({
          tenant: $routeParams.tenant,
          "switch": switchUUID
        }).$promise.then(function(networks) {
          $scope.instance.vnics[index].networks = networks;
          return $scope.renewAddresses('', index);
        });
      };
      $scope.assignVolume = function(volume) {
        volume.selected = true;
        return $scope.instance['vdisks'].push({
          'desired': {
            'volume': volume.desired.uuid,
            'instance': '%instance_uuid%',
            'index': $scope.instance['vdisks'].length + 1
          },
          'volume': volume
        });
      };
      $scope.unassignVolume = function(volume) {
        var item, _i, _len, _ref;
        _ref = $scope.volumes;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          if (volume.desired.uuid === item.desired.uuid) {
            item.selected = false;
          }
        }
        return $scope.instance['vdisks'] = $scope.instance['vdisks'].filter(function(item) {
          return item.volume.desired.uuid !== volume.desired.uuid;
        });
      };
    }

    return InstanceWizardCtrl;

  })());

}).call(this);
