// Generated by CoffeeScript 1.6.3
(function() {
  var HostListCtrl, module;

  module = angular.module('host', []);

  module.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/host/', {
        templateUrl: 'platform/host/host-list.tpl.html',
        controller: HostListCtrl
      });
    }
  ]);

  module.controller('HostListCtrl', HostListCtrl = (function() {
    HostListCtrl.inject = ['$scope', 'Host', 'dataContainer'];

    function HostListCtrl($scope, Host, dataContainer) {
      Host.list().$promise.then(function(i) {
        $scope.hosts = i;
        return dataContainer.registerEntity('host', $scope.hosts);
      });
    }

    return HostListCtrl;

  })());

}).call(this);
