// Generated by CoffeeScript 1.7.1

/*
Directive that rewrites value of a given model to 'null'
if the value of a model is an empty string
 */

(function() {
  var module;

  module = angular.module('rainbowDirectives');

  module.directive('emptyToNull', function($parse) {
    return {
      restrict: 'A',
      require: 'ngModel',
      link: function(scope, element, attrs, ctrl) {
        return ctrl.$parsers.push(function(viewValue) {
          if (viewValue != null) {
            if (viewValue === "") {
              return null;
            }
            return viewValue;
          }
        });
      }
    };
  });

}).call(this);
