// Generated by CoffeeScript 1.7.1

/*
Directive for adding simple checkboxes to tables and create buttons like Delete all.

Usage:

Wrap whole table with some element (like div) with pc-multiactions attribute
directive (no value).

Add <th pc-multiall /></th> to your table header where you need 'select all'
checkbox.

In your ng-repeat add <td pc-multicheck="{{ affinityGroup.desired.uuid }}"></td>to insert checkbox to select that item. Value of multicheck directive should be identifier of given item. This will be returned by getSelected() method.

Add button for your action and pass result of getSelected() to your function.

You can use <pc-multieditbutton ></pc-multieditbutton> to add button that turns on/off edit mode.

Example:

<div pc-multiactions>
    <pc-multieditbutton ></pc-multieditbutton>
    <table class="table table-striped table-responsive table-hover">
    <tr>
     <th pc-multiall></th>
     <th>Name</th>
    </tr>
    <tr ng-repeat="item in items">
        <td pc-multicheck="{{ item.ud }}"></td>
        <td>...</td>
    </tr>
    </table>
    <button class="btn btn-danger" ng-click="deleteSelected(getSelected())">
         <i class="icon-plus-sign icon-white"></i>Delete selected
    </button>
</div>
 */

(function() {
  var module;

  module = angular.module('rainbowDirectives');

  module.directive('pcMultiactions', function($parse, $filter, $compile) {
    return {
      restrict: 'A',
      scope: true,
      link: function(scope, element, attrs) {
        scope.selected = [];
        scope.editMode = false;
        return scope.all = [];
      },
      controller: function($scope) {
        var search;
        $scope.select = function(id) {
          var pos;
          if (!$scope.isSelected(id)) {
            $scope.selected.push(id);
            return $scope.selected = _.uniq($scope.selected);
          } else {
            pos = $scope.selected.indexOf(id);
            return $scope.selected.splice(pos, 1);
          }
        };
        $scope.isSelected = function(id) {
          return $scope.selected.indexOf(id) > -1;
        };
        $scope.isAllSelected = function() {
          var item, _i, _len, _ref;
          $scope.all = _.uniq($scope.all);
          _ref = $scope.all;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            item = _ref[_i];
            if (!$scope.filterSearch($scope.selected, item)) {
              return false;
            }
          }
          return true;
        };
        $scope.getSelected = function() {
          return $scope.selected;
        };
        $scope.selectAll = function() {
          if ($scope.isAllSelected()) {
            return $scope.selected = [];
          } else {
            return $scope.selected = $scope.all.slice(0);
          }
        };
        $scope.filterSearch = function(dict, pattern) {
          var k;
          for (k in dict) {
            if (typeof dict[k] === "object") {
              if ($scope.filterSearch(dict[k], pattern)) {
                return true;
              }
            } else if (dict[k] === pattern) {
              return true;
            }
          }
          return false;
        };
        $scope.switchEdit = function() {
          return $scope.editMode = !$scope.editMode;
        };
        search = function(dict, pattern) {
          var k;
          for (k in dict) {
            if (typeof dict[k] === "object") {
              if (search(dict[k], pattern)) {
                return true;
              }
            } else if (dict[k] === pattern) {
              return true;
            }
          }
          return false;
        };
        this.addToAll = function(id) {
          return $scope.all.push(id);
        };
      }
    };
  });

  module.directive('pcMulticheck', function($parse, $filter, $compile) {
    return {
      restrict: 'A',
      scope: true,
      require: '^pcMultiactions',
      replace: true,
      link: function(scope, element, attrs, ctrl) {
        scope.itemKey = attrs['pcMulticheck'];
        return ctrl.addToAll(scope.itemKey);
      },
      template: '<td ng-show="editMode"> <button type="button" class="btn btn-default btn-xs" ng-click="select(itemKey)" ng-class="{\'btn-danger\': isSelected(itemKey)}"> <span class="fa fa-check" ng-class="{\'fa-inverse\': !isSelected(itemKey)}"> </span> </button> </td>'
    };
  });

  module.directive('pcMultiall', function($parse, $filter, $compile) {
    return {
      restrict: 'A',
      scope: true,
      require: '^pcMultiactions',
      replace: true,
      template: '<th ng-show="editMode"> <button type="button" class="btn btn-default btn-xs" ng-click="selectAll()"· ng-class="{\'btn-danger\': isAllSelected()}"> <span class="fa fa-check"· ng-class="{\'fa-inverse\': !isAllSelected()}"> </span> </button> </td>'
    };
  });

  module.directive('pcMultieditbutton', function($parse, $filter, $compile) {
    return {
      restrict: 'E',
      scope: true,
      require: '^pcMultiactions',
      replace: true,
      template: '<button type="button" class="btn btn-info" ng-click="switchEdit()" ng-switch on="editMode"> <span ng-switch-when="false">Edit</span> <span ng-switch-when="true">Cancel</span> </button>'
    };
  });

}).call(this);
