// Generated by CoffeeScript 1.6.3
(function() {
  var module;

  module = angular.module('rainbowDirectives', []);

  module.directive('networkInterfaces', function() {
    return {
      restrict: 'E',
      templateUrl: '../common/directives/network-interfaces.html',
      require: '?ngModel',
      replace: true,
      scope: {
        ngModel: '=',
        saveFunction: '='
      },
      link: function(scope, element, attrs) {
        scope.$watch('ngModel.nics', function() {
          var index, nic, _i, _len, _ref, _results;
          if (scope.ngModel.nics != null) {
            _ref = scope.ngModel.nics;
            _results = [];
            for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
              nic = _ref[index];
              _results.push(scope.availableNics[nic.desired.hwaddr] = {
                enabled: true
              });
            }
            return _results;
          }
        });
        return scope.$watch('ngModel.bonds', function() {
          var bond, nic, _i, _len, _ref, _results;
          if (scope.ngModel.bonds != null) {
            _ref = scope.ngModel.bonds;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              bond = _ref[_i];
              bond.desired.roles.$promise.then(function(roles) {
                var role, _j, _len1, _results1;
                _results1 = [];
                for (_j = 0, _len1 = roles.length; _j < _len1; _j++) {
                  role = roles[_j];
                  _results1.push(scope.availableRoles[role.desired.role].enabled = false);
                }
                return _results1;
              });
              _results.push((function() {
                var _j, _len1, _ref1, _results1;
                _ref1 = bond.desired.nics;
                _results1 = [];
                for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                  nic = _ref1[_j];
                  _results1.push(scope.availableNics[nic.desired.hwaddr].enabled = false);
                }
                return _results1;
              })());
            }
            return _results;
          }
        });
      },
      controller: function($scope) {
        $scope.roleDefaults = {};
        $scope.availableNics = {};
        $scope.availableRoles = {
          "public": {
            name: "Public",
            enabled: true
          },
          management: {
            name: "Management",
            enabled: true
          },
          storage: {
            name: "Storage",
            enabled: true
          },
          virtual: {
            name: "Virtual",
            enabled: true
          },
          core: {
            name: "Core",
            enabled: true
          }
        };
        $scope.addNicRole = function(bond, role) {
          var new_role;
          if ($scope.availableRoles[role].enabled) {
            new_role = {
              desired: {
                role: role,
                address: null
              }
            };
            if ($scope.roleDefaults[role]) {
              new_role.desired.vlan_id = $scope.roleDefaults[role].vlan_id;
              new_role.desired.address = $scope.roleDefaults[role].address;
            }
            bond.desired.roles.push(new_role);
            return $scope.availableRoles[role].enabled = false;
          }
        };
        $scope.removeNicRole = function(bond, index) {
          var role;
          console.log('remove----');
          console.log(index);
          role = bond.desired.roles[index].desired;
          $scope.roleDefaults[role.role] = {
            vlan_id: role.vlan_id,
            address: role.address
          };
          $scope.availableRoles[role.role].enabled = true;
          return bond.desired.roles.splice(index, 1);
        };
        $scope.removeNicRole = function(bond, index) {
          var role;
          role = bond.desired.roles[index].desired;
          $scope.roleDefaults[role.role] = {
            vlan_id: role.vlan_id,
            address: role.address
          };
          $scope.availableRoles[role.role].enabled = true;
          return bond.desired.roles.splice(index, 1);
        };
        $scope.addNic = function(bond, mac) {
          if ($scope.availableNics[mac].enabled) {
            bond.desired.nics.push({
              desired: {
                hwaddr: mac
              }
            });
            return $scope.availableNics[mac].enabled = false;
          }
        };
        $scope.addAllAvailableResources = function(bond, resource) {
          var add_function, item, key, res, _results;
          res = resource === 'nic' ? $scope.availableNics : $scope.availableRoles;
          add_function = resource === 'nic' ? $scope.addNic : $scope.addNicRole;
          _results = [];
          for (key in res) {
            item = res[key];
            if (item.enabled) {
              _results.push(add_function(bond, key));
            }
          }
          return _results;
        };
        $scope.removeNic = function(bond, index) {
          var nic;
          nic = bond.desired.nics[index];
          $scope.availableNics[nic.desired.hwaddr].enabled = true;
          return bond.desired.nics.splice(index, 1);
        };
        $scope.removeAggregation = function(index) {
          var bond, i, _i, _ref;
          bond = $scope.ngModel.bonds[index];
          for (i = _i = _ref = bond.desired.roles.length - 1; _ref <= 0 ? _i <= 0 : _i >= 0; i = _ref <= 0 ? ++_i : --_i) {
            $scope.removeNicRole(bond, i);
          }
          return $scope.ngModel.bonds.splice(index, 1);
        };
        $scope.createAggregation = function() {
          return $scope.ngModel.bonds.push({
            desired: {
              mode: 'active-backup',
              roles: [],
              nics: []
            }
          });
        };
        $scope.hasAvailableResource = function(resource) {
          var count, item, res;
          res = resource === "nic" ? $scope.availableNics : $scope.availableRoles;
          count = 0;
          for (item in res) {
            if (item.enabled) {
              count++;
            }
          }
          return count > 0;
        };
        $scope.saveNetwork = function() {
          return $scope.saveFunction();
        };
        return $('#availableItemsAffix').affix({
          offset: 55
        });
      }
    };
  });

}).call(this);
