// Generated by CoffeeScript 1.6.3
(function() {
  var module;

  module = angular.module('rainbowDirectives');

  module.directive('state', function() {
    return {
      restrict: 'E',
      templateUrl: 'partials/directives/state.html',
      require: '?ngModel',
      scope: {
        model: '=ngModel',
        attr: '@ngAttr'
      },
      replace: true,
      controller: function() {}
    };
  });

}).call(this);
