// Generated by CoffeeScript 1.7.1
(function() {
  var VolumeDetailCtrl, VolumeListCtrl, module;

  module = angular.module('tenantVolume', ['rainbowServices']);

  module.config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/:tenant/volume', {
        templateUrl: 'tenant/volume/volume-list.tpl.html',
        controller: 'VolumeListCtrl'
      });
      return $routeProvider.when('/:tenant/volume/:volume', {
        templateUrl: 'tenant/volume/volume-detail.tpl.html',
        controller: 'VolumeDetailCtrl'
      });
    }
  ]);

  module.controller('VolumeListCtrl', VolumeListCtrl = (function() {
    VolumeListCtrl.inject = ['$scope', '$rootScope', '$routeParams', 'TenantVolume', 'StoragePool', 'dataContainer', '$modal'];

    function VolumeListCtrl($scope, $rootScope, $routeParams, TenantVolume, StoragePool, dataContainer, $modal) {
      TenantVolume.list({
        'tenant': $routeParams.tenant
      }).$promise.then(function(VolumeList) {
        $scope.volumes = VolumeList;
        return dataContainer.registerEntity('volume', $scope.volumes);
      });
      $scope.$watch('volumes', function(value) {
        console.log('Filtering volumes...');
        return $scope.filteredVolumes = $scope.volumes.filter(function(item) {
          if (!item.desired.image) {
            return item;
          }
        });
      }, true);
      StoragePool.list().$promise.then(function(StoragePoolList) {
        $scope.storagepools = StoragePoolList;
        return dataContainer.registerEntity('storagepool', $scope.storagepools);
      });
      $scope.filterType = function(actual, expected) {
        expected = expected.toLowerCase();
        if ((actual != null) && 'image'.search(expected) > -1) {
          return true;
        }
        if ((actual == null) && 'volume'.search(expected) > -1) {
          return true;
        }
        return false;
      };
      $scope.volumeModal = $modal({
        scope: $scope,
        template: 'tenant/volume/volume-modal.tpl.html',
        show: false
      });
      $scope.open = function() {
        $scope.volume = {
          'storagepools': {}
        };
        return $scope.volumeModal.show();
      };
      $scope.close = function() {
        $scope.volumeModal.hide();
        return false;
      };
      $scope.createVolume = function() {
        var newVolume;
        newVolume = new TenantVolume();
        newVolume.desired = {
          'name': $scope.volume.name,
          'state': 'present',
          'size': $scope.volume.size,
          'storage_pool': $scope.volume.storagepool
        };
        return newVolume.$save({
          'tenant': $routeParams.tenant
        }, function(response) {
          return $scope.close();
        });
      };
      $scope.deleteVolume = function(uuid) {
        var params;
        params = {
          'tenant': $routeParams.tenant,
          'volume': uuid
        };
        return TenantVolume["delete"](params, function() {
          return $scope.message("Volume deleted", 'success');
        });
      };
      $scope.deleteSelected = function(items) {
        var item, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = items.length; _i < _len; _i++) {
          item = items[_i];
          _results.push($scope.deleteVolume(item));
        }
        return _results;
      };
    }

    return VolumeListCtrl;

  })());

  module.controller('VolumeDetailCtrl', VolumeDetailCtrl = (function() {
    VolumeDetailCtrl.inject = ['$scope', '$rootScope', '$routeParams', 'TenantVolume', 'TenantVolumeVdisk', 'TenantInstance', 'dataContainer', '$modal'];

    function VolumeDetailCtrl($scope, $routeParams, TenantVolume, TenantVolumeVdisk, TenantInstance, dataContainer, $modal, $route) {
      var criteria;
      criteria = {
        'tenant': $routeParams.tenant,
        'volume': $routeParams.volume
      };
      TenantVolume.get(criteria).$promise.then(function(volume) {
        $scope.volume = volume;
        return dataContainer.registerResource($scope.volume, $scope.volume.desired.uuid);
      });
      TenantVolumeVdisk.list({
        'tenant': $routeParams.tenant,
        'volume': $routeParams.volume
      }).$promise.then(function(vdisks) {
        $scope.vdisks = vdisks;
        dataContainer.registerEntity('vdisk', $scope.vdisks);
        return $scope.$watch('vdisks', function(value) {
          return $scope.filteredVdisks = $scope.vdisks.filter(function(item) {
            if (item.desired.volume === $routeParams.volume) {
              return item;
            }
          });
        }, true);
      });
      TenantInstance.list({
        'tenant': $routeParams.tenant
      }).$promise.then(function(instances) {
        $scope.instances = instances;
        dataContainer.registerEntity('instance', $scope.instance);
        return $scope.$watch('instances', function(value) {
          var instance, _i, _len, _results;
          $scope.instanceDict = {};
          _results = [];
          for (_i = 0, _len = value.length; _i < _len; _i++) {
            instance = value[_i];
            _results.push($scope.instanceDict[instance.desired.uuid] = instance);
          }
          return _results;
        });
      });
      $scope.volumeEditModal = $modal({
        scope: $scope,
        template: 'tenant/volume/volume-edit-modal.tpl.html',
        show: false
      });
      $scope.open = function() {
        return $scope.volumeEditModal.show();
      };
      $scope.close = function() {
        $scope.volumeEditModal.hide();
        return false;
      };
      $scope.unlink = function(volume) {
        var params, patch;
        patch = JSON.stringify([
          {
            'op': 'x-merge',
            'path': '/desired',
            'value': {
              'volume': null
            }
          }
        ]);
        params = {
          'tenant': $routeParams.tenant,
          'volume': volume.desired.uuid
        };
        return TenantVolume.patch(params, patch, function() {
          return $scope.backVolumes.splice($scope.backVolumes.indexOf(volume), 1);
        });
      };
      $scope.editVolume = function() {
        var params, patch;
        patch = JSON.stringify([
          {
            'op': 'x-merge',
            'path': '/desired',
            'value': {
              'name': $scope.volume.desired.name,
              'size': $scope.volume.desired.size
            }
          }
        ]);
        params = {
          'tenant': $routeParams.tenant,
          'volume': $routeParams.volume
        };
        return TenantVolume.patch(params, patch, function() {
          return $scope.close();
        });
      };
    }

    return VolumeDetailCtrl;

  })());

}).call(this);
