// Generated by CoffeeScript 1.7.1
(function() {
  var NetworkDetailCtrl, module;

  module = angular.module('tenantNetwork', ['rainbowServices']);

  module.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/:tenant/switch/:switch/network/:network', {
        templateUrl: 'tenant/network/network-detail.tpl.html',
        controller: 'NetworkDetailCtrl'
      });
    }
  ]);

  module.controller('NetworkDetailCtrl', NetworkDetailCtrl = (function() {
    NetworkDetailCtrl.inject = ['$scope', '$rootScope', '$routeParams', 'TenantSwitchNetwork', 'TenantSwitchNetworkRoute', 'dataContainer', '$modal'];

    function NetworkDetailCtrl($scope, $routeParams, TenantSwitchNetwork, TenantSwitchNetworkRoute, dataContainer, $modal) {
      TenantSwitchNetwork.get({
        'tenant': $routeParams.tenant,
        'switch': $routeParams["switch"],
        'network': $routeParams.network
      }).$promise.then(function(network) {
        $scope.network = network;
        return dataContainer.registerResource($scope.network, $scope.network.desired.uuid);
      });
      TenantSwitchNetworkRoute.list({
        'tenant': $routeParams.tenant,
        'switch': $routeParams["switch"],
        'network': $routeParams.network
      }).$promise.then(function(routes) {
        $scope.routes = routes;
        return dataContainer.registerEntity('route', $scope.routes);
      });
      $scope.routeModal = $modal({
        scope: $scope,
        template: 'tenant/network/route-modal.tpl.html',
        show: false
      });
      $scope.createRoute = function() {
        var newRoute;
        newRoute = new TenantSwitchNetworkRoute();
        newRoute.desired = {
          'route': $scope.route.route,
          'via': $scope.route.via
        };
        return newRoute.$save({
          'tenant': $routeParams.tenant,
          'switch': $routeParams["switch"],
          'network': $routeParams.network
        }, function(response) {
          return $scope.routeModalClose();
        });
      };
      $scope.deleteSelectedRoutes = function(items) {
        var item, params, patch, _i, _len;
        patch = [];
        params = {
          tenant: $routeParams.tenant,
          "switch": $routeParams["switch"],
          network: $routeParams.network
        };
        for (_i = 0, _len = items.length; _i < _len; _i++) {
          item = items[_i];
          patch.push({
            'op': 'remove',
            'path': '/' + item
          });
        }
        return TenantSwitchNetworkRoute.patch(params, patch);
      };
      $scope.routeModalOpen = function() {
        $scope.routeModal.show();
        return $scope.route = {};
      };
      $scope.routeModalClose = function() {
        return $scope.routeModal.hide();
      };
    }

    return NetworkDetailCtrl;

  })());

}).call(this);
