// Generated by CoffeeScript 1.6.3
(function() {
  var MainCtrl, module;

  module = angular.module('commonControllers', ['rainbowServices']);

  module.controller('MainCtrl', MainCtrl = (function() {
    MainCtrl.inject = ['$scope', '$rootScope', '$routeParams', '$location', 'dataContainer', '$route', 'auth', 'Tenant'];

    function MainCtrl($scope, $rootScope, $routeParams, $location, dataContainer, $route, auth, Tenant) {
      this.$scope = $scope;
      this.$rootScope = $rootScope;
      this.$routeParams = $routeParams;
      this.$location = $location;
      $scope.currentTenant = $routeParams;
      $scope.socketsActive = false;
      if (!auth.isLogged()) {
        $location.path("/login");
      }
      auth.initTokens();
      $scope.$on('$routeChangeSuccess', function() {
        $scope.activePath = $location.path().split('/').pop();
        $scope.path = $location.path().split('/');
        if (auth.isLogged() && !$scope.socketsActive) {
          dataContainer.listenSocket();
        }
        if ($scope.tenant !== $routeParams.tenant && $routeParams.tenant) {
          dataContainer.subscribeTenant($routeParams.tenant);
        }
        $scope.tenant = $routeParams.tenant;
        return $rootScope.layoutPartial = function() {
          var currentTenant;
          if ($route.current['layoutPartial']) {
            return '../common/layouts/' + $route.current['layoutPartial'];
          } else {
            return '../common/layouts/default.html';
          }
          if ($scope.tenant) {
            currentTenant = Tenant.get({
              'tenant': $routeParams.tenant
            }, function() {
              if ($scope.currentTenantName !== currentTenant.desired.name) {
                return $scope.currentTenantName = currentTenant.desired.name;
              }
            });
          }
          return $rootScope.messages = [];
        };
      });
      $rootScope.message = function() {
        $rootScope.messages.unshift({
          'text': text,
          'type': type
        });
        if ($rootScope.messages.length > 1) {
          return $rootScope.messages.pop();
        }
      };
    }

    return MainCtrl;

  })());

}).call(this);
