// Generated by CoffeeScript 1.7.1
(function() {
  var ClusterDetailCtrl, ClusterListCtrl, module;

  module = angular.module('tenant-cluster', ['rainbowServices']);

  module.config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/:tenant/cluster', {
        templateUrl: 'tenant/cluster/cluster-list.tpl.html',
        controller: 'ClusterListCtrl'
      });
      return $routeProvider.when('/:tenant/cluster/:cluster', {
        templateUrl: 'tenant/cluster/cluster-detail.tpl.html',
        controller: 'ClusterDetailCtrl'
      });
    }
  ]);

  module.controller('ClusterListCtrl', ClusterListCtrl = (function() {
    ClusterListCtrl.inject = ['$scope', '$rootScope', '$routeParams', 'TenantCluster', 'dataContainer'];

    function ClusterListCtrl($scope, $rootScope, $routeParams, TenantCluster, dataContainer) {
      TenantCluster.list({
        'tenant': $routeParams.tenant
      }).$promise.then(function(clusterList) {
        $scope.clusters = clusterList;
        return dataContainer.registerEntity('cluster', $scope.clusters);
      });
      $scope.opts = {
        backdropFade: true,
        dialogFade: true
      };
      $scope.open = function(cluster) {
        $scope.clusterModal = true;
        if (typeof cluster !== 'undefined') {
          return $scope.cluster = cluster.desired;
        } else {
          return $scope.cluster = null;
        }
      };
      $scope.close = function() {
        $scope.closeMsg = 'I was closed at: ' + new Date();
        $scope.clusterModal = false;
        return false;
      };
      $scope.createCluster = function() {
        var newCluster;
        newCluster = new TenantCluster();
        newCluster.desired = {
          'name': $scope.cluster.name
        };
        return newCluster.$save({
          'tenant': $routeParams.tenant
        }, function(response) {
          return $scope.clusters.push({
            'desired': {
              'uuid': response.uuids.POST,
              'name': $scope.cluster.name
            }
          });
        });
      };
      $scope.modifyCluster = function() {
        if (typeof $scope.cluster.uuid === 'undefined') {
          $scope.createCluster();
        } else {
          $scope.editCluster();
        }
        return $scope.close();
      };
      $scope.editCluster = function() {
        var params, patch;
        patch = JSON.stringify([
          {
            'op': 'x-merge',
            'path': '/desired',
            'value': {
              'name': $scope.cluster.name
            }
          }
        ]);
        params = {
          'tenant': $routeParams.tenant,
          'cluster': $scope.cluster.uuid
        };
        return TenantCluster.patch(params, patch, function() {
          return $scope.message("Cluster modified", 'success');
        });
      };
      $scope.deleteCluster = function(cluster, index) {
        var params, position;
        position = $scope.clusters.indexOf(cluster);
        params = {
          'tenant': $routeParams.tenant,
          'cluster': cluster.desired.uuid
        };
        return TenantCluster["delete"](params, function() {
          $scope.clusters.splice(position, 1);
          return $scope.message("Cluster deleted", 'success');
        });
      };
    }

    return ClusterListCtrl;

  })());

  module.controller('ClusterDetailCtrl', ClusterDetailCtrl = (function() {
    ClusterDetailCtrl.inject = ['$scope', '$rootScope', '$routeParams', 'TenantCluster', 'dataContainer'];

    function ClusterDetailCtrl($scope, $routeParams, TenantCluster, TenantClusterInstanceJoin) {
      $scope.cluster = TenantCluster.get({
        'tenant': $routeParams.tenant,
        'cluster': $routeParams.cluster
      });
      $scope.instances = TenantClusterInstanceJoin.list({
        'tenant': $routeParams.tenant,
        'cluster': $routeParams.cluster
      });
    }

    return ClusterDetailCtrl;

  })());

}).call(this);
