// Generated by CoffeeScript 1.7.1
(function() {
  var app_module, module;

  module = angular.module('jm.i18next');

  module.config([
    '$i18nextProvider', function($i18nextProvider) {
      return $i18nextProvider.options = {
        lng: 'en',
        useCookie: false,
        useLocalStorage: false,
        fallbackLng: 'dev',
        resGetPath: '../common/locales/__lng__/__ns__.json'
      };
    }
  ]);

  app_module = angular.module('app', ['ngSanitize', 'ngRoute', 'ngAnimate', 'mgcrea.ngStrap', 'jm.i18next', 'mgo-angular-wizard', 'ui.sortable', 'tenantInstance', 'tenantAffinityGroup', 'tenantSwitch', 'tenantNetwork', 'platformTenant', 'commonControllers', 'rainbowServices', 'rainbowDirectives', 'tenantImage', 'tenantDashboard', 'hostNetwork', 'appLogin', 'host']);

  app_module.config([
    '$routeProvider', '$locationProvider', function($routeProvider, $locationProvider) {
      return $routeProvider.otherwise({
        redirectTo: '/tenant'
      });
    }
  ]);

  app_module.run([
    '$rootScope', '$route', function($rootScope, $route) {
      return $rootScope.messages = [];
    }
  ]);

}).call(this);
