// Generated by CoffeeScript 1.7.1
(function() {
  var SwitchDetailCtrl, SwitchListCtrl, module;

  module = angular.module('tenantSwitch', ['rainbowServices']);

  module.config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/:tenant/switch', {
        templateUrl: 'tenant/switch/switch-list.tpl.html',
        controller: 'SwitchListCtrl'
      });
      return $routeProvider.when('/:tenant/switch/:switch', {
        templateUrl: 'tenant/switch/switch-detail.tpl.html',
        controller: 'SwitchDetailCtrl'
      });
    }
  ]);

  module.controller('SwitchListCtrl', SwitchListCtrl = (function() {
    SwitchListCtrl.inject = ['$scope', '$rootScope', '$routeParams', 'TenantSwitch', 'dataContainer'];

    function SwitchListCtrl($scope, $rootScope, $routeParams, TenantSwitch, dataContainer, $modal, $location) {
      this.$location = $location;
      TenantSwitch.list({
        'tenant': $routeParams.tenant
      }).$promise.then(function(switchList) {
        $scope.switches = switchList;
        return dataContainer.registerEntity('switch', $scope.switches);
      });
      $scope.switchListModal = $modal({
        scope: $scope,
        template: 'tenant/switch/switch-list-modal.tpl.html',
        show: false
      });
      $scope.open = function() {
        $scope.switchListModal.show();
        return $scope["switch"] = {};
      };
      $scope.close = function() {
        $scope.closeMsg = 'I was closed at: ' + new Date();
        $scope.switchListModal.hide();
        return false;
      };
      $scope.createSwitch = function() {
        var newSwitch;
        newSwitch = new TenantSwitch();
        newSwitch.desired = {
          'name': $scope["switch"].name,
          'type': $scope["switch"].type
        };
        return newSwitch.$save({
          'tenant': $routeParams.tenant
        }, function(response) {
          $scope["switch"].uuid = response.uuids.POST;
          $scope.switches.push({
            'desired': $scope["switch"]
          });
          return $scope.switchListModal.hide();
        });
      };
      $scope.deleteSwitch = function(uuid) {
        var params;
        params = {
          'tenant': $routeParams.tenant,
          'switch': uuid
        };
        return TenantSwitch["delete"](params, function() {
          return $scope.switches = $scope.switches.filter(function(item) {
            return item.desired.uuid !== uuid;
          });
        });
      };
      $scope.deleteSelected = function(items) {
        var item, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = items.length; _i < _len; _i++) {
          item = items[_i];
          _results.push($scope.deleteSwitch(item));
        }
        return _results;
      };
    }

    return SwitchListCtrl;

  })());

  module.controller('SwitchDetailCtrl', SwitchDetailCtrl = (function() {
    SwitchDetailCtrl.inject = ['$scope', '$rootScope', '$routeParams', 'TenantSwitch', 'TenantSwitchNetwork', 'dataContainer', '$modal'];

    function SwitchDetailCtrl($scope, $routeParams, TenantSwitch, TenantSwitchNetwork, $modal) {
      $scope["switch"] = TenantSwitch.get({
        'tenant': $routeParams.tenant,
        'switch': $routeParams["switch"]
      });
      $scope.networks = TenantSwitchNetwork.list({
        'tenant': $routeParams.tenant,
        'switch': $routeParams["switch"]
      });
      $scope.switchEditModal = $modal({
        keyboard: true,
        scope: $scope,
        template: 'tenant/switch/switch-edit-modal.tpl.html',
        show: false
      });
      $scope.networkModal = $modal({
        keyboard: true,
        scope: $scope,
        template: 'tenant/switch/network-list-modal.tpl.html',
        show: false
      });
      $scope.editSwitch = function() {
        var params, patch;
        patch = JSON.stringify([
          {
            'op': 'x-merge',
            'path': '/desired',
            'value': {
              'name': $scope["switch"].desired.name,
              'type': $scope["switch"].desired.type,
              'tag': $scope["switch"].desired.tag === '' ? null : $scope["switch"].desired.tag
            }
          }
        ]);
        params = {
          'tenant': $routeParams.tenant,
          'switch': $scope["switch"].desired.uuid
        };
        return TenantSwitch.patch(params, patch, function() {
          $scope.close(true);
          return $scope.message("Switch modified", 'success');
        });
      };
      $scope.open = function() {
        return $scope.switchEditModal.show();
      };
      $scope.close = function(suppress_update) {
        if (suppress_update == null) {
          suppress_update = false;
        }
        $scope.switchEditModal.hide();
        if (!suppress_update) {
          $scope["switch"] = TenantSwitch.get({
            'tenant': $routeParams.tenant,
            'switch': $routeParams["switch"]
          });
        }
        return false;
      };
      $scope.createNetwork = function() {
        var newNetwork;
        newNetwork = new TenantSwitchNetwork();
        newNetwork.desired = {
          'range': $scope.network.range,
          'vlan_tag': $scope.network.vlan_tag
        };
        return newNetwork.$save({
          'tenant': $routeParams.tenant,
          'switch': $routeParams["switch"]
        }, function(response) {
          $scope.network.uuid = response.uuids.POST;
          $scope.networks.push({
            'desired': $scope.network
          });
          return $scope.networkModal.hide();
        });
      };
      $scope.deleteNetwork = function(uuid) {
        var params;
        params = {
          'tenant': $routeParams.tenant,
          'switch': $routeParams["switch"],
          'network': uuid
        };
        return TenantSwitchNetwork["delete"](params, function() {
          return $scope.networks = $scope.networks.filter(function(item) {
            return item.desired.uuid !== uuid;
          });
        });
      };
      $scope.deleteSelectedNetworks = function(items) {
        var item, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = items.length; _i < _len; _i++) {
          item = items[_i];
          _results.push($scope.deleteNetwork(item));
        }
        return _results;
      };
      $scope.networkModalOpen = function() {
        $scope.networkModal.show();
        return $scope.network = {};
      };
      $scope.networkModalClose = function() {
        return $scope.networkModal.hide();
      };
    }

    return SwitchDetailCtrl;

  })());

}).call(this);
