// Generated by CoffeeScript 1.6.3
(function() {
  var TenanatDashboardCtrl, module;

  module = angular.module('tenant-dashboard', []);

  module.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/:tenant/dashboard', {
        templateUrl: 'tenant/tenant-dashboard.tpl.html',
        conroller: 'TenantDashboardCtrl'
      });
    }
  ]);

  module.controller('TenantDashboardCtrl', TenanatDashboardCtrl = (function() {
    TenanatDashboardCtrl.$inject = ['$scope', '$routeParams', 'Tenant'];

    function TenanatDashboardCtrl($scope, $routeParams, Tenant) {
      $scope.tenant = Tenant.get({
        tenant: $routeParams.tenant
      });
    }

    return TenanatDashboardCtrl;

  })());

}).call(this);
