// Generated by CoffeeScript 1.6.3
(function() {
  var factoryFunction, module;

  module = angular.module('rainbowServices', ['rainbowConfig']);

  factoryFunction = function($timeout, WEB_URL, API_SUFFIX) {
    return {
      serverUrl: WEB_URL + API_SUFFIX,
      getToken: function(id) {
        return localStorage.getItem(id + '-token');
      },
      getTokenValidity: function(id) {
        return localStorage.getItem(id + '-valid');
      },
      isTokenValid: function(id) {
        return this.getTokenValidity(id) > Date.now() / 1000;
      },
      getUserToken: function() {
        return this.getToken('user');
      },
      getTenantToken: function(tenant) {
        var id, response, token;
        id = 'tenant-' + tenant;
        token = this.getToken(id);
        if ((token == null) || !this.isTokenValid(id)) {
          response = this.retreiveToken('tenant', this.getUserToken(), tenant);
          this.setToken(id, response);
        }
        return this.getToken(id);
      },
      retreiveToken: function(type, auth, tenant) {
        var authHeader, authUrl, responseText;
        if (type === 'tenant') {
          authHeader = 'Token ' + auth;
          authUrl = this.serverUrl + '/tenant/' + tenant + '/token';
        } else if (type === 'user-token') {
          authHeader = 'Token ' + auth;
          authUrl = this.serverUrl + '/token';
        } else {
          authHeader = 'Basic ' + auth;
          authUrl = this.serverUrl + '/token';
        }
        responseText = $.ajax({
          type: "GET",
          url: authUrl,
          async: false,
          headers: {
            'Authentication': authHeader
          },
          dataType: 'json'
        }).responseText;
        return JSON.parse(responseText);
      },
      setToken: function(id, data) {
        localStorage.setItem(id + '-token', data.token);
        localStorage.setItem(id + '-valid', data.valid);
        return this.setRefreshTokenTimer(id);
      },
      setRefreshTokenTimer: function(id) {
        var doRefresh, timeout;
        if (!this.getToken(id) || !this.isTokenValid(id)) {
          return false;
        }
        timeout = (this.getTokenValidity(id) * 1000 - Date.now()) * 0.9;
        doRefresh = function(me) {
          return function() {
            return me.refreshToken(id);
          };
        };
        return $timeout(doRefresh(this), timeout);
      },
      refreshToken: function(id) {
        var token;
        if (id === 'user') {
          token = this.retreiveToken('user-token', this.getUserToken());
        } else {
          token = this.retreiveToken('tenant', this.getUserToken(), id.replace('tenant-', ''));
        }
        return this.setToken(id, token);
      },
      login: function(name, password) {
        var auth, token;
        auth = window.btoa(name + ':' + password);
        token = this.retreiveToken('user', auth);
        this.setToken('user', token);
        return token;
      },
      isLogged: function() {
        return this.getUserToken() && this.isTokenValid('user');
      }
    };
  };

  module.factory('auth', factoryFunction);

}).call(this);
