// Generated by CoffeeScript 1.6.3
(function() {
  var factoryFunction, module;

  module = angular.module('rainbowServices', ['rainbowConfig']);

  factoryFunction = function($q, $timeout, WEB_URL, API_SUFFIX) {
    return {
      serverUrl: WEB_URL + API_SUFFIX,
      userTokenPromise: $q.defer(),
      getToken: function(id) {
        return localStorage.getItem(id + '-token');
      },
      getTokenValidity: function(id) {
        return localStorage.getItem(id + '-valid');
      },
      isTokenValid: function(id) {
        return this.getTokenValidity(id) > Date.now() / 1000;
      },
      getUserToken: function() {
        return this.userTokenPromise.promise;
      },
      getTenantToken: function(tenant) {
        var id, promise, token, userToken,
          _this = this;
        id = 'tenant-' + tenant;
        token = this.getToken(id);
        promise = $q.defer();
        if ((token == null) || !this.isTokenValid(id)) {
          userToken = this.getUserToken();
          userToken.then(function(userTokenValue) {
            var response;
            response = _this.retreiveToken('tenant', userTokenValue, tenant);
            return response.then(function(data) {
              _this.setToken(id, data.data);
              return promise.resolve(data.data.token);
            });
          });
        } else {
          promise.resolve(token);
        }
        return promise.promise;
      },
      retreiveToken: function(type, auth, tenant) {
        var authHeader, authUrl, injector;
        if (type === 'tenant') {
          authHeader = 'Token ' + auth;
          authUrl = this.serverUrl + '/tenant/' + tenant + '/token';
        } else if (type === 'user-token') {
          authHeader = 'Token ' + auth;
          authUrl = this.serverUrl + '/token';
        } else {
          authHeader = 'Basic ' + auth;
          authUrl = this.serverUrl + '/token';
        }
        injector = angular.injector(['ng']);
        return injector.invoke(function($http) {
          var requestConfig;
          requestConfig = {
            headers: {
              'Authorization': authHeader
            }
          };
          return $http.get(authUrl, requestConfig);
        });
      },
      setToken: function(id, data) {
        localStorage.setItem(id + '-token', data.token);
        localStorage.setItem(id + '-valid', data.valid);
        if (id === 'user') {
          this.userTokenPromise.resolve(data.token);
          this.userTokenPromise = $q.defer();
          this.userTokenPromise.resolve(data.token);
        }
        return this.setRefreshTokenTimer(id);
      },
      setRefreshTokenTimer: function(id) {
        var doRefresh, timeout;
        if (!this.getToken(id) || !this.isTokenValid(id)) {
          return false;
        }
        timeout = (this.getTokenValidity(id) * 1000 - Date.now()) * 0.9;
        doRefresh = function(me) {
          return function() {
            return me.refreshToken(id);
          };
        };
        return $timeout(doRefresh(this), timeout);
      },
      refreshToken: function(id) {
        var token, userToken,
          _this = this;
        userToken = this.getToken('user');
        if (id === 'user') {
          token = this.retreiveToken('user-token', userToken);
        } else {
          token = this.retreiveToken('tenant', userToken, id.replace('tenant-', ''));
        }
        return token.then(function(tokenData) {
          return _this.setToken(id, tokenData.data);
        });
      },
      login: function(name, password) {
        var auth, token,
          _this = this;
        auth = window.btoa(name + ':' + password);
        token = this.retreiveToken('user', auth);
        return token.then(function(response) {
          return _this.setToken('user', response.data);
        });
      },
      isLogged: function() {
        return (this.getToken('user') != null) && this.isTokenValid('user');
      },
      initTokens: function() {
        var i, key, tenantSearch, tenantUuid, _i, _ref, _results;
        if (this.isLogged()) {
          this.userTokenPromise.resolve(this.getToken('user'));
          this.setRefreshTokenTimer('user');
        }
        _results = [];
        for (i = _i = 0, _ref = localStorage.length; _i < _ref; i = _i += 1) {
          key = localStorage.key(i);
          tenantSearch = /tenant-([0-9a-z-]*)-token/;
          tenantUuid = tenantSearch.exec(key);
          if (tenantUuid != null) {
            _results.push(this.setRefreshTokenTimer('tenant-' + tenantUuid[1]));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };
  };

  module.factory('auth', factoryFunction);

}).call(this);
