// Generated by CoffeeScript 1.6.3
(function() {
  var factoryFunction, module;

  module = angular.module('rainbowServices', ['ng', 'rainbowResource', 'rainbowPatchApi']);

  factoryFunction = function($http, $q, $timeout) {
    return {
      serverUrl: 'http://localhost:8080/api/v1',
      getUserToken: function() {
        return localStorage.getItem('user');
      },
      getTenantToken: function(tenant) {
        var me, promise, token;
        token = localStorage.getItem('tenant-' + tenant);
        if (!token || token.valid < Date.now()) {
          promise = $http.get(this.serverUrl + '/tenant/' + tenant + '/token', {
            'headers': {
              'Authorization': 'Token ' + this.getUserToken()
            }
          });
          me = this;
          $q.all([promise]).then(function(items) {
            console.log(items[0].data.token);
            return me.setTenantToken(tenant, JSON.stringify(items[0].data));
          });
          return JSON.parse(localStorage.getItem("tenant-" + tenant))['token'];
        }
        return JSON.parse(token)['token'];
      },
      setUserToken: function(token) {
        var timeout;
        localStorage.setItem('user', token.token);
        console.log(token);
        timeout = token.valid * 1000 - new Date().getTime() - 30 * 1000;
        return console.log('Refresh timeout ', timeout);
      },
      refreshUserToken: function() {
        var auth;
        auth = 'Token ' + this.getUserToken();
        return this.getToken(auth);
      },
      setUserTokenRefreshTimeout: function() {},
      setTenantToken: function(tenant, token) {
        return localStorage.setItem("tenant-" + tenant, token);
      },
      clearAllTokens: function() {
        return localStorage.clear();
      },
      getUsername: function() {
        return localStorage.getItem('username');
      },
      login: function(name, password) {
        var auth;
        localStorage.setItem('username', name);
        auth = 'Basic ' + window.btoa(name + ':' + password);
        return this.getToken(auth);
      },
      getToken: function(auth) {
        return $http.get(this.serverUrl + '/token', {
          'headers': {
            'Authorization': auth
          }
        });
      },
      isLogged: function() {
        var _ref;
        return (_ref = this.getUserToken()) != null ? _ref : false;
      }
    };
  };

  module.factory('auth', factoryFunction);

}).call(this);
