// Generated by CoffeeScript 1.6.3
(function() {
  var module;

  module = angular.module('rainbow.config', []);

  module.constant('WEB_URL', 'http://localhost:8080');

  module.constant('WEB_PORT', '8080');

  module.constant('WS_URL', 'ws://localhost:9000');

  module.constant('WS_PORT', '9000');

  module.constant('API_SUFFIX', '/api/v1');

}).call(this);
