// Generated by CoffeeScript 1.6.3
(function() {
  var Address, Api, Bond, Cluster, Config, CpuProfile, Disk, Entity, Event, Host, Image, Instance, Member, Network, Nic, Quota, Role, Route, StoragePool, Switch, Tenant, User, Vdisk, Vnic, Volume, s, _ref, _ref1, _ref10, _ref11, _ref12, _ref13, _ref14, _ref15, _ref16, _ref17, _ref18, _ref19, _ref2, _ref20, _ref21, _ref22, _ref23, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Entity = (function() {
    Entity.serial = 0;

    Entity.prototype.path = '';

    Entity.prototype.ops = [];

    Entity.prototype.parent = null;

    Entity.prototype.id = null;

    Entity.prototype.pkey = null;

    Entity._incrementSerial = function() {
      return Entity.serial++;
    };

    function Entity(parent, path, id) {
      this.parent = parent;
      this.path = path;
      this.id = id;
      if (!this.id) {
        this.id = "%autoid" + Entity.serial;
        Entity.serial++;
      }
    }

    Entity.prototype._getPath = function() {
      return this.path;
    };

    Entity.prototype._replaceId = function(path, id) {
      var r;
      r = path.replace(/%id/g, id ? id : this.id);
      r = r.replace("//", "/");
      return r;
    };

    Entity.prototype._fixValue = function(value, pkey, id) {
      return value;
    };

    Entity.prototype._add = function(op, path, value, pkey, id) {
      value = this._fixValue(value, pkey, id);
      if (this.parent) {
        return this.parent._add(op, this._replaceId(this._getPath()) + this._replaceId(path, id), value);
      } else {
        return this.ops.push({
          op: op,
          path: this._replaceId(path, id),
          value: value
        });
      }
    };

    Entity.prototype._remove = function(path, id) {
      if (this.parent) {
        return this.parent._remove(this._replaceId(this._getPath()) + this._replaceId(path, id));
      } else {
        return this.ops.push({
          op: 'remove',
          path: this._replaceId(path, id)
        });
      }
    };

    Entity.prototype._replace = function(path, id, newData) {
      if (this.parent) {
        return this.parent._replace(this._replaceId(this._getPath()) + this._replaceId(path, id, newData), id, newData);
      } else {
        return this.ops.push({
          op: 'replace',
          path: this._replaceId(path, id),
          value: newData
        });
      }
    };

    Entity.prototype._merge = function(path, id, newData) {
      if (this.parent) {
        return this.parent._merge(this._replaceId(this._getPath()) + this._replaceId(path, id, newData), id, newData);
      } else {
        return this.ops.push({
          op: 'x-merge',
          path: this._replaceId(path, id),
          value: newData
        });
      }
    };

    return Entity;

  })();

  StoragePool = (function(_super) {
    __extends(StoragePool, _super);

    function StoragePool() {
      _ref = StoragePool.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    StoragePool.prototype.addVolume = function(data, id) {
      var _volume;
      _volume = new Volume(this, "/children/volume/%id/");
      this._add("add", "/children/volume/%id", data, "uuid", _volume.id);
      return _volume;
    };

    StoragePool.prototype.removeVolume = function(uuid) {
      return this._remove("/children/volume/%id", uuid);
    };

    StoragePool.prototype.replaceVolume = function(uuid, newData) {
      return this._replace("/children/volume/%id/desired", uuid, newData);
    };

    StoragePool.prototype.mergeVolume = function(uuid, newData) {
      return this._merge("/children/volume/%id/desired", uuid, newData);
    };

    StoragePool.prototype.Volume = function(id) {
      return new Volume(this, "/children/volume/%id/", id);
    };

    StoragePool.prototype.addDisk = function(data, id) {
      var _disk;
      _disk = new Disk(this, "/children/disk/%id/");
      this._add("add", "/children/disk/%id", data, "id", _disk.id);
      return _disk;
    };

    StoragePool.prototype.removeDisk = function(uuid) {
      return this._remove("/children/disk/%id", uuid);
    };

    StoragePool.prototype.replaceDisk = function(uuid, newData) {
      return this._replace("/children/disk/%id/desired", uuid, newData);
    };

    StoragePool.prototype.mergeDisk = function(uuid, newData) {
      return this._merge("/children/disk/%id/desired", uuid, newData);
    };

    StoragePool.prototype.Disk = function(id) {
      return new Disk(this, "/children/disk/%id/", id);
    };

    return StoragePool;

  })(Entity);

  Image = (function(_super) {
    __extends(Image, _super);

    function Image() {
      _ref1 = Image.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Image.prototype.addVolume = function(data, id) {
      var _volume;
      _volume = new Volume(this, "/children/volume/%id/");
      this._add("add", "/children/volume/%id", data, "uuid", _volume.id);
      return _volume;
    };

    Image.prototype.removeVolume = function(uuid) {
      return this._remove("/children/volume/%id", uuid);
    };

    Image.prototype.replaceVolume = function(uuid, newData) {
      return this._replace("/children/volume/%id/desired", uuid, newData);
    };

    Image.prototype.mergeVolume = function(uuid, newData) {
      return this._merge("/children/volume/%id/desired", uuid, newData);
    };

    Image.prototype.Volume = function(id) {
      return new Volume(this, "/children/volume/%id/", id);
    };

    return Image;

  })(Entity);

  Cluster = (function(_super) {
    __extends(Cluster, _super);

    function Cluster() {
      _ref2 = Cluster.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    return Cluster;

  })(Entity);

  Disk = (function(_super) {
    __extends(Disk, _super);

    function Disk() {
      _ref3 = Disk.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    return Disk;

  })(Entity);

  Event = (function(_super) {
    __extends(Event, _super);

    function Event() {
      _ref4 = Event.__super__.constructor.apply(this, arguments);
      return _ref4;
    }

    return Event;

  })(Entity);

  Network = (function(_super) {
    __extends(Network, _super);

    function Network() {
      _ref5 = Network.__super__.constructor.apply(this, arguments);
      return _ref5;
    }

    Network.prototype.addRoute = function(data, id) {
      var _route;
      _route = new Route(this, "/children/route/%id/");
      this._add("add", "/children/route/%id", data, "uuid", _route.id);
      return _route;
    };

    Network.prototype.removeRoute = function(uuid) {
      return this._remove("/children/route/%id", uuid);
    };

    Network.prototype.replaceRoute = function(uuid, newData) {
      return this._replace("/children/route/%id/desired", uuid, newData);
    };

    Network.prototype.mergeRoute = function(uuid, newData) {
      return this._merge("/children/route/%id/desired", uuid, newData);
    };

    Network.prototype.Route = function(id) {
      return new Route(this, "/children/route/%id/", id);
    };

    Network.prototype.addAddress = function(data, id) {
      var _address;
      _address = new Address(this, "/children/address/%id/");
      this._add("add", "/children/address/%id", data, "uuid", _address.id);
      return _address;
    };

    Network.prototype.removeAddress = function(uuid) {
      return this._remove("/children/address/%id", uuid);
    };

    Network.prototype.replaceAddress = function(uuid, newData) {
      return this._replace("/children/address/%id/desired", uuid, newData);
    };

    Network.prototype.mergeAddress = function(uuid, newData) {
      return this._merge("/children/address/%id/desired", uuid, newData);
    };

    Network.prototype.Address = function(id) {
      return new Address(this, "/children/address/%id/", id);
    };

    return Network;

  })(Entity);

  CpuProfile = (function(_super) {
    __extends(CpuProfile, _super);

    function CpuProfile() {
      _ref6 = CpuProfile.__super__.constructor.apply(this, arguments);
      return _ref6;
    }

    return CpuProfile;

  })(Entity);

  Vdisk = (function(_super) {
    __extends(Vdisk, _super);

    function Vdisk() {
      _ref7 = Vdisk.__super__.constructor.apply(this, arguments);
      return _ref7;
    }

    return Vdisk;

  })(Entity);

  Member = (function(_super) {
    __extends(Member, _super);

    function Member() {
      _ref8 = Member.__super__.constructor.apply(this, arguments);
      return _ref8;
    }

    return Member;

  })(Entity);

  Instance = (function(_super) {
    __extends(Instance, _super);

    function Instance() {
      _ref9 = Instance.__super__.constructor.apply(this, arguments);
      return _ref9;
    }

    return Instance;

  })(Entity);

  Role = (function(_super) {
    __extends(Role, _super);

    function Role() {
      _ref10 = Role.__super__.constructor.apply(this, arguments);
      return _ref10;
    }

    return Role;

  })(Entity);

  Config = (function(_super) {
    __extends(Config, _super);

    function Config() {
      _ref11 = Config.__super__.constructor.apply(this, arguments);
      return _ref11;
    }

    return Config;

  })(Entity);

  Vnic = (function(_super) {
    __extends(Vnic, _super);

    function Vnic() {
      _ref12 = Vnic.__super__.constructor.apply(this, arguments);
      return _ref12;
    }

    return Vnic;

  })(Entity);

  Nic = (function(_super) {
    __extends(Nic, _super);

    function Nic() {
      _ref13 = Nic.__super__.constructor.apply(this, arguments);
      return _ref13;
    }

    return Nic;

  })(Entity);

  Quota = (function(_super) {
    __extends(Quota, _super);

    function Quota() {
      _ref14 = Quota.__super__.constructor.apply(this, arguments);
      return _ref14;
    }

    return Quota;

  })(Entity);

  Volume = (function(_super) {
    __extends(Volume, _super);

    function Volume() {
      _ref15 = Volume.__super__.constructor.apply(this, arguments);
      return _ref15;
    }

    return Volume;

  })(Entity);

  Host = (function(_super) {
    __extends(Host, _super);

    function Host() {
      _ref16 = Host.__super__.constructor.apply(this, arguments);
      return _ref16;
    }

    Host.prototype.addStoragePool = function(data, id) {
      var _storagepool;
      _storagepool = new StoragePool(this, "/children/storage-pool/%id/");
      this._add("add", "/children/storage-pool/%id", data, "[u'host', u'storage_pool']", _storagepool.id);
      return _storagepool;
    };

    Host.prototype.removeStoragePool = function(uuid) {
      return this._remove("/children/storage-pool/%id", uuid);
    };

    Host.prototype.replaceStoragePool = function(uuid, newData) {
      return this._replace("/children/storage-pool/%id/desired", uuid, newData);
    };

    Host.prototype.mergeStoragePool = function(uuid, newData) {
      return this._merge("/children/storage-pool/%id/desired", uuid, newData);
    };

    Host.prototype.StoragePool = function(id) {
      return new StoragePool(this, "/children/storage-pool/%id/", id);
    };

    Host.prototype.addInstance = function(data, id) {
      var _instance;
      _instance = new Instance(this, "/children/instance/%id/");
      this._add("add", "/children/instance/%id", data, "[u'host', u'instance']", _instance.id);
      return _instance;
    };

    Host.prototype.removeInstance = function(uuid) {
      return this._remove("/children/instance/%id", uuid);
    };

    Host.prototype.replaceInstance = function(uuid, newData) {
      return this._replace("/children/instance/%id/desired", uuid, newData);
    };

    Host.prototype.mergeInstance = function(uuid, newData) {
      return this._merge("/children/instance/%id/desired", uuid, newData);
    };

    Host.prototype.Instance = function(id) {
      return new Instance(this, "/children/instance/%id/", id);
    };

    Host.prototype.addNic = function(data, id) {
      var _nic;
      _nic = new Nic(this, "/children/nic/%id/");
      this._add("add", "/children/nic/%id", data, "hwaddr", _nic.id);
      return _nic;
    };

    Host.prototype.removeNic = function(uuid) {
      return this._remove("/children/nic/%id", uuid);
    };

    Host.prototype.replaceNic = function(uuid, newData) {
      return this._replace("/children/nic/%id/desired", uuid, newData);
    };

    Host.prototype.mergeNic = function(uuid, newData) {
      return this._merge("/children/nic/%id/desired", uuid, newData);
    };

    Host.prototype.Nic = function(id) {
      return new Nic(this, "/children/nic/%id/", id);
    };

    Host.prototype.addImage = function(data, id) {
      var _image;
      _image = new Image(this, "/children/image/%id/");
      this._add("add", "/children/image/%id", data, "[u'host', u'image']", _image.id);
      return _image;
    };

    Host.prototype.removeImage = function(uuid) {
      return this._remove("/children/image/%id", uuid);
    };

    Host.prototype.replaceImage = function(uuid, newData) {
      return this._replace("/children/image/%id/desired", uuid, newData);
    };

    Host.prototype.mergeImage = function(uuid, newData) {
      return this._merge("/children/image/%id/desired", uuid, newData);
    };

    Host.prototype.Image = function(id) {
      return new Image(this, "/children/image/%id/", id);
    };

    Host.prototype.addVolume = function(data, id) {
      var _volume;
      _volume = new Volume(this, "/children/volume/%id/");
      this._add("add", "/children/volume/%id", data, "[u'host', u'volume']", _volume.id);
      return _volume;
    };

    Host.prototype.removeVolume = function(uuid) {
      return this._remove("/children/volume/%id", uuid);
    };

    Host.prototype.replaceVolume = function(uuid, newData) {
      return this._replace("/children/volume/%id/desired", uuid, newData);
    };

    Host.prototype.mergeVolume = function(uuid, newData) {
      return this._merge("/children/volume/%id/desired", uuid, newData);
    };

    Host.prototype.Volume = function(id) {
      return new Volume(this, "/children/volume/%id/", id);
    };

    Host.prototype.addCpuProfile = function(data, id) {
      var _cpuprofile;
      _cpuprofile = new CpuProfile(this, "/children/cpu-profile/%id/");
      this._add("add", "/children/cpu-profile/%id", data, "[u'host', u'cpu_profile']", _cpuprofile.id);
      return _cpuprofile;
    };

    Host.prototype.removeCpuProfile = function(uuid) {
      return this._remove("/children/cpu-profile/%id", uuid);
    };

    Host.prototype.replaceCpuProfile = function(uuid, newData) {
      return this._replace("/children/cpu-profile/%id/desired", uuid, newData);
    };

    Host.prototype.mergeCpuProfile = function(uuid, newData) {
      return this._merge("/children/cpu-profile/%id/desired", uuid, newData);
    };

    Host.prototype.CpuProfile = function(id) {
      return new CpuProfile(this, "/children/cpu-profile/%id/", id);
    };

    Host.prototype.addDisk = function(data, id) {
      var _disk;
      _disk = new Disk(this, "/children/disk/%id/");
      this._add("add", "/children/disk/%id", data, "[u'host', u'disk']", _disk.id);
      return _disk;
    };

    Host.prototype.removeDisk = function(uuid) {
      return this._remove("/children/disk/%id", uuid);
    };

    Host.prototype.replaceDisk = function(uuid, newData) {
      return this._replace("/children/disk/%id/desired", uuid, newData);
    };

    Host.prototype.mergeDisk = function(uuid, newData) {
      return this._merge("/children/disk/%id/desired", uuid, newData);
    };

    Host.prototype.Disk = function(id) {
      return new Disk(this, "/children/disk/%id/", id);
    };

    Host.prototype.addEvent = function(data, id) {
      var _event;
      _event = new Event(this, "/children/event/%id/");
      this._add("add", "/children/event/%id", data, "hash", _event.id);
      return _event;
    };

    Host.prototype.removeEvent = function(uuid) {
      return this._remove("/children/event/%id", uuid);
    };

    Host.prototype.replaceEvent = function(uuid, newData) {
      return this._replace("/children/event/%id/desired", uuid, newData);
    };

    Host.prototype.mergeEvent = function(uuid, newData) {
      return this._merge("/children/event/%id/desired", uuid, newData);
    };

    Host.prototype.Event = function(id) {
      return new Event(this, "/children/event/%id/", id);
    };

    Host.prototype.addBond = function(data, id) {
      var _bond;
      _bond = new Bond(this, "/children/bond/%id/");
      this._add("add", "/children/bond/%id", data, "uuid", _bond.id);
      return _bond;
    };

    Host.prototype.removeBond = function(uuid) {
      return this._remove("/children/bond/%id", uuid);
    };

    Host.prototype.replaceBond = function(uuid, newData) {
      return this._replace("/children/bond/%id/desired", uuid, newData);
    };

    Host.prototype.mergeBond = function(uuid, newData) {
      return this._merge("/children/bond/%id/desired", uuid, newData);
    };

    Host.prototype.Bond = function(id) {
      return new Bond(this, "/children/bond/%id/", id);
    };

    return Host;

  })(Entity);

  User = (function(_super) {
    __extends(User, _super);

    function User() {
      _ref17 = User.__super__.constructor.apply(this, arguments);
      return _ref17;
    }

    User.prototype.addMember = function(data, id) {
      var _member;
      _member = new Member(this, "/children/member/%id/");
      this._add("add", "/children/member/%id", data, "uuid", _member.id);
      return _member;
    };

    User.prototype.removeMember = function(uuid) {
      return this._remove("/children/member/%id", uuid);
    };

    User.prototype.replaceMember = function(uuid, newData) {
      return this._replace("/children/member/%id/desired", uuid, newData);
    };

    User.prototype.mergeMember = function(uuid, newData) {
      return this._merge("/children/member/%id/desired", uuid, newData);
    };

    User.prototype.Member = function(id) {
      return new Member(this, "/children/member/%id/", id);
    };

    return User;

  })(Entity);

  Address = (function(_super) {
    __extends(Address, _super);

    function Address() {
      _ref18 = Address.__super__.constructor.apply(this, arguments);
      return _ref18;
    }

    return Address;

  })(Entity);

  Tenant = (function(_super) {
    __extends(Tenant, _super);

    function Tenant() {
      _ref19 = Tenant.__super__.constructor.apply(this, arguments);
      return _ref19;
    }

    Tenant.prototype.addMember = function(data, id) {
      var _member;
      _member = new Member(this, "/children/member/%id/");
      this._add("add", "/children/member/%id", data, "uuid", _member.id);
      return _member;
    };

    Tenant.prototype.removeMember = function(uuid) {
      return this._remove("/children/member/%id", uuid);
    };

    Tenant.prototype.replaceMember = function(uuid, newData) {
      return this._replace("/children/member/%id/desired", uuid, newData);
    };

    Tenant.prototype.mergeMember = function(uuid, newData) {
      return this._merge("/children/member/%id/desired", uuid, newData);
    };

    Tenant.prototype.Member = function(id) {
      return new Member(this, "/children/member/%id/", id);
    };

    Tenant.prototype.addInstance = function(data, id) {
      var _instance;
      _instance = new Instance(this, "/children/instance/%id/");
      this._add("add", "/children/instance/%id", data, "uuid", _instance.id);
      return _instance;
    };

    Tenant.prototype.removeInstance = function(uuid) {
      return this._remove("/children/instance/%id", uuid);
    };

    Tenant.prototype.replaceInstance = function(uuid, newData) {
      return this._replace("/children/instance/%id/desired", uuid, newData);
    };

    Tenant.prototype.mergeInstance = function(uuid, newData) {
      return this._merge("/children/instance/%id/desired", uuid, newData);
    };

    Tenant.prototype.Instance = function(id) {
      return new Instance(this, "/children/instance/%id/", id);
    };

    Tenant.prototype.addImage = function(data, id) {
      var _image;
      _image = new Image(this, "/children/image/%id/");
      this._add("add", "/children/image/%id", data, "uuid", _image.id);
      return _image;
    };

    Tenant.prototype.removeImage = function(uuid) {
      return this._remove("/children/image/%id", uuid);
    };

    Tenant.prototype.replaceImage = function(uuid, newData) {
      return this._replace("/children/image/%id/desired", uuid, newData);
    };

    Tenant.prototype.mergeImage = function(uuid, newData) {
      return this._merge("/children/image/%id/desired", uuid, newData);
    };

    Tenant.prototype.Image = function(id) {
      return new Image(this, "/children/image/%id/", id);
    };

    Tenant.prototype.addQuota = function(data, id) {
      var _quota;
      _quota = new Quota(this, "/children/quota/%id/");
      this._add("add", "/children/quota/%id", data, "uuid", _quota.id);
      return _quota;
    };

    Tenant.prototype.removeQuota = function(uuid) {
      return this._remove("/children/quota/%id", uuid);
    };

    Tenant.prototype.replaceQuota = function(uuid, newData) {
      return this._replace("/children/quota/%id/desired", uuid, newData);
    };

    Tenant.prototype.mergeQuota = function(uuid, newData) {
      return this._merge("/children/quota/%id/desired", uuid, newData);
    };

    Tenant.prototype.Quota = function(id) {
      return new Quota(this, "/children/quota/%id/", id);
    };

    Tenant.prototype.addVolume = function(data, id) {
      var _volume;
      _volume = new Volume(this, "/children/volume/%id/");
      this._add("add", "/children/volume/%id", data, "uuid", _volume.id);
      return _volume;
    };

    Tenant.prototype.removeVolume = function(uuid) {
      return this._remove("/children/volume/%id", uuid);
    };

    Tenant.prototype.replaceVolume = function(uuid, newData) {
      return this._replace("/children/volume/%id/desired", uuid, newData);
    };

    Tenant.prototype.mergeVolume = function(uuid, newData) {
      return this._merge("/children/volume/%id/desired", uuid, newData);
    };

    Tenant.prototype.Volume = function(id) {
      return new Volume(this, "/children/volume/%id/", id);
    };

    Tenant.prototype.addCluster = function(data, id) {
      var _cluster;
      _cluster = new Cluster(this, "/children/cluster/%id/");
      this._add("add", "/children/cluster/%id", data, "uuid", _cluster.id);
      return _cluster;
    };

    Tenant.prototype.removeCluster = function(uuid) {
      return this._remove("/children/cluster/%id", uuid);
    };

    Tenant.prototype.replaceCluster = function(uuid, newData) {
      return this._replace("/children/cluster/%id/desired", uuid, newData);
    };

    Tenant.prototype.mergeCluster = function(uuid, newData) {
      return this._merge("/children/cluster/%id/desired", uuid, newData);
    };

    Tenant.prototype.Cluster = function(id) {
      return new Cluster(this, "/children/cluster/%id/", id);
    };

    Tenant.prototype.addSwitch = function(data, id) {
      var _switch;
      _switch = new Switch(this, "/children/switch/%id/");
      this._add("add", "/children/switch/%id", data, "uuid", _switch.id);
      return _switch;
    };

    Tenant.prototype.removeSwitch = function(uuid) {
      return this._remove("/children/switch/%id", uuid);
    };

    Tenant.prototype.replaceSwitch = function(uuid, newData) {
      return this._replace("/children/switch/%id/desired", uuid, newData);
    };

    Tenant.prototype.mergeSwitch = function(uuid, newData) {
      return this._merge("/children/switch/%id/desired", uuid, newData);
    };

    Tenant.prototype.Switch = function(id) {
      return new Switch(this, "/children/switch/%id/", id);
    };

    return Tenant;

  })(Entity);

  Route = (function(_super) {
    __extends(Route, _super);

    function Route() {
      _ref20 = Route.__super__.constructor.apply(this, arguments);
      return _ref20;
    }

    return Route;

  })(Entity);

  Switch = (function(_super) {
    __extends(Switch, _super);

    function Switch() {
      _ref21 = Switch.__super__.constructor.apply(this, arguments);
      return _ref21;
    }

    Switch.prototype.addVnic = function(data, id) {
      var _vnic;
      _vnic = new Vnic(this, "/children/vnic/%id/");
      this._add("add", "/children/vnic/%id", data, "uuid", _vnic.id);
      return _vnic;
    };

    Switch.prototype.removeVnic = function(uuid) {
      return this._remove("/children/vnic/%id", uuid);
    };

    Switch.prototype.replaceVnic = function(uuid, newData) {
      return this._replace("/children/vnic/%id/desired", uuid, newData);
    };

    Switch.prototype.mergeVnic = function(uuid, newData) {
      return this._merge("/children/vnic/%id/desired", uuid, newData);
    };

    Switch.prototype.Vnic = function(id) {
      return new Vnic(this, "/children/vnic/%id/", id);
    };

    Switch.prototype.addNetwork = function(data, id) {
      var _network;
      _network = new Network(this, "/children/network/%id/");
      this._add("add", "/children/network/%id", data, "uuid", _network.id);
      return _network;
    };

    Switch.prototype.removeNetwork = function(uuid) {
      return this._remove("/children/network/%id", uuid);
    };

    Switch.prototype.replaceNetwork = function(uuid, newData) {
      return this._replace("/children/network/%id/desired", uuid, newData);
    };

    Switch.prototype.mergeNetwork = function(uuid, newData) {
      return this._merge("/children/network/%id/desired", uuid, newData);
    };

    Switch.prototype.Network = function(id) {
      return new Network(this, "/children/network/%id/", id);
    };

    return Switch;

  })(Entity);

  Bond = (function(_super) {
    __extends(Bond, _super);

    function Bond() {
      _ref22 = Bond.__super__.constructor.apply(this, arguments);
      return _ref22;
    }

    Bond.prototype.addNic = function(data, id) {
      var _nic;
      _nic = new Nic(this, "/children/nic/%id/");
      this._add("add", "/children/nic/%id", data, "hwaddr", _nic.id);
      return _nic;
    };

    Bond.prototype.removeNic = function(uuid) {
      return this._remove("/children/nic/%id", uuid);
    };

    Bond.prototype.replaceNic = function(uuid, newData) {
      return this._replace("/children/nic/%id/desired", uuid, newData);
    };

    Bond.prototype.mergeNic = function(uuid, newData) {
      return this._merge("/children/nic/%id/desired", uuid, newData);
    };

    Bond.prototype.Nic = function(id) {
      return new Nic(this, "/children/nic/%id/", id);
    };

    Bond.prototype.addRole = function(data, id) {
      var _role;
      _role = new Role(this, "/children/role/%id/");
      this._add("add", "/children/role/%id", data, "uuid", _role.id);
      return _role;
    };

    Bond.prototype.removeRole = function(uuid) {
      return this._remove("/children/role/%id", uuid);
    };

    Bond.prototype.replaceRole = function(uuid, newData) {
      return this._replace("/children/role/%id/desired", uuid, newData);
    };

    Bond.prototype.mergeRole = function(uuid, newData) {
      return this._merge("/children/role/%id/desired", uuid, newData);
    };

    Bond.prototype.Role = function(id) {
      return new Role(this, "/children/role/%id/", id);
    };

    return Bond;

  })(Entity);

  Api = (function(_super) {
    __extends(Api, _super);

    function Api() {
      _ref23 = Api.__super__.constructor.apply(this, arguments);
      return _ref23;
    }

    Api.patchStoragePool = function(_storagepool) {
      return new StoragePool(null, "/storage-pool/" + _storagepool + "/", _storagepool);
    };

    Api.patchStoragePoolVolume = function(_storagepool, _volume) {
      return new Volume(null, "/storage-pool/" + _storagepool + "/volume/" + _volume + "/", _volume);
    };

    Api.patchStoragePoolDisk = function(_storagepool, _disk) {
      return new Disk(null, "/storage-pool/" + _storagepool + "/disk/" + _disk + "/", _disk);
    };

    Api.patchImage = function(_image) {
      return new Image(null, "/image/" + _image + "/", _image);
    };

    Api.patchImageVolume = function(_image, _volume) {
      return new Volume(null, "/image/" + _image + "/volume/" + _volume + "/", _volume);
    };

    Api.patchSwitch = function(_switch) {
      return new Switch(null, "/switch/" + _switch + "/", _switch);
    };

    Api.patchSwitchVnic = function(_switch, _vnic) {
      return new Vnic(null, "/switch/" + _switch + "/vnic/" + _vnic + "/", _vnic);
    };

    Api.patchSwitchNetwork = function(_switch, _network) {
      return new Network(null, "/switch/" + _switch + "/network/" + _network + "/", _network);
    };

    Api.patchSwitchNetworkRoute = function(_switch, _network, _route) {
      return new Route(null, "/switch/" + _switch + "/network/" + _network + "/route/" + _route + "/", _route);
    };

    Api.patchSwitchNetworkAddress = function(_switch, _network, _address) {
      return new Address(null, "/switch/" + _switch + "/network/" + _network + "/address/" + _address + "/", _address);
    };

    Api.patchCpuProfile = function(_cpuprofile) {
      return new CpuProfile(null, "/cpu-profile/" + _cpuprofile + "/", _cpuprofile);
    };

    Api.patchHost = function(_host) {
      return new Host(null, "/host/" + _host + "/", _host);
    };

    Api.patchHostStoragePool = function(_host, _storagepool) {
      return new StoragePool(null, "/host/" + _host + "/storage-pool/" + _storagepool + "/", _storagepool);
    };

    Api.patchHostInstance = function(_host, _instance) {
      return new Instance(null, "/host/" + _host + "/instance/" + _instance + "/", _instance);
    };

    Api.patchHostNic = function(_host, _nic) {
      return new Nic(null, "/host/" + _host + "/nic/" + _nic + "/", _nic);
    };

    Api.patchHostImage = function(_host, _image) {
      return new Image(null, "/host/" + _host + "/image/" + _image + "/", _image);
    };

    Api.patchHostVolume = function(_host, _volume) {
      return new Volume(null, "/host/" + _host + "/volume/" + _volume + "/", _volume);
    };

    Api.patchHostCpuProfile = function(_host, _cpuprofile) {
      return new CpuProfile(null, "/host/" + _host + "/cpu-profile/" + _cpuprofile + "/", _cpuprofile);
    };

    Api.patchHostDisk = function(_host, _disk) {
      return new Disk(null, "/host/" + _host + "/disk/" + _disk + "/", _disk);
    };

    Api.patchHostEvent = function(_host, _event) {
      return new Event(null, "/host/" + _host + "/event/" + _event + "/", _event);
    };

    Api.patchHostBond = function(_host, _bond) {
      return new Bond(null, "/host/" + _host + "/bond/" + _bond + "/", _bond);
    };

    Api.patchHostBondNic = function(_host, _bond, _nic) {
      return new Nic(null, "/host/" + _host + "/bond/" + _bond + "/nic/" + _nic + "/", _nic);
    };

    Api.patchHostBondRole = function(_host, _bond, _role) {
      return new Role(null, "/host/" + _host + "/bond/" + _bond + "/role/" + _role + "/", _role);
    };

    Api.patchUser = function(_user) {
      return new User(null, "/user/" + _user + "/", _user);
    };

    Api.patchUserMember = function(_user, _member) {
      return new Member(null, "/user/" + _user + "/member/" + _member + "/", _member);
    };

    Api.patchDisk = function(_disk) {
      return new Disk(null, "/disk/" + _disk + "/", _disk);
    };

    Api.patchConfig = function(_config) {
      return new Config(null, "/config/" + _config + "/", _config);
    };

    Api.patchEvent = function(_event) {
      return new Event(null, "/event/" + _event + "/", _event);
    };

    Api.patchTenant = function(_tenant) {
      return new Tenant(null, "/tenant/" + _tenant + "/", _tenant);
    };

    Api.patchTenantMember = function(_tenant, _member) {
      return new Member(null, "/tenant/" + _tenant + "/member/" + _member + "/", _member);
    };

    Api.patchTenantInstance = function(_tenant, _instance) {
      return new Instance(null, "/tenant/" + _tenant + "/instance/" + _instance + "/", _instance);
    };

    Api.patchTenantInstanceVdisk = function(_tenant, _instance, _vdisk) {
      return new Vdisk(null, "/tenant/" + _tenant + "/instance/" + _instance + "/vdisk/" + _vdisk + "/", _vdisk);
    };

    Api.patchTenantInstanceCluster = function(_tenant, _instance, _cluster) {
      return new Cluster(null, "/tenant/" + _tenant + "/instance/" + _instance + "/cluster/" + _cluster + "/", _cluster);
    };

    Api.patchTenantInstanceVnic = function(_tenant, _instance, _vnic) {
      return new Vnic(null, "/tenant/" + _tenant + "/instance/" + _instance + "/vnic/" + _vnic + "/", _vnic);
    };

    Api.patchTenantInstanceVnicAddress = function(_tenant, _instance, _vnic, _address) {
      return new Address(null, "/tenant/" + _tenant + "/instance/" + _instance + "/vnic/" + _vnic + "/address/" + _address + "/", _address);
    };

    Api.patchTenantInstanceEvent = function(_tenant, _instance, _event) {
      return new Event(null, "/tenant/" + _tenant + "/instance/" + _instance + "/event/" + _event + "/", _event);
    };

    Api.patchTenantImage = function(_tenant, _image) {
      return new Image(null, "/tenant/" + _tenant + "/image/" + _image + "/", _image);
    };

    Api.patchTenantImageVolume = function(_tenant, _image, _volume) {
      return new Volume(null, "/tenant/" + _tenant + "/image/" + _image + "/volume/" + _volume + "/", _volume);
    };

    Api.patchTenantQuota = function(_tenant, _quota) {
      return new Quota(null, "/tenant/" + _tenant + "/quota/" + _quota + "/", _quota);
    };

    Api.patchTenantVolume = function(_tenant, _volume) {
      return new Volume(null, "/tenant/" + _tenant + "/volume/" + _volume + "/", _volume);
    };

    Api.patchTenantVolumeVdisk = function(_tenant, _volume, _vdisk) {
      return new Vdisk(null, "/tenant/" + _tenant + "/volume/" + _volume + "/vdisk/" + _vdisk + "/", _vdisk);
    };

    Api.patchTenantCluster = function(_tenant, _cluster) {
      return new Cluster(null, "/tenant/" + _tenant + "/cluster/" + _cluster + "/", _cluster);
    };

    Api.patchTenantClusterInstance = function(_tenant, _cluster, _instance) {
      return new Instance(null, "/tenant/" + _tenant + "/cluster/" + _cluster + "/instance/" + _instance + "/", _instance);
    };

    Api.patchTenantSwitch = function(_tenant, _switch) {
      return new Switch(null, "/tenant/" + _tenant + "/switch/" + _switch + "/", _switch);
    };

    Api.patchTenantSwitchVnic = function(_tenant, _switch, _vnic) {
      return new Vnic(null, "/tenant/" + _tenant + "/switch/" + _switch + "/vnic/" + _vnic + "/", _vnic);
    };

    Api.patchTenantSwitchNetwork = function(_tenant, _switch, _network) {
      return new Network(null, "/tenant/" + _tenant + "/switch/" + _switch + "/network/" + _network + "/", _network);
    };

    Api.patchTenantSwitchNetworkRoute = function(_tenant, _switch, _network, _route) {
      return new Route(null, "/tenant/" + _tenant + "/switch/" + _switch + "/network/" + _network + "/route/" + _route + "/", _route);
    };

    Api.patchTenantSwitchNetworkAddress = function(_tenant, _switch, _network, _address) {
      return new Address(null, "/tenant/" + _tenant + "/switch/" + _switch + "/network/" + _network + "/address/" + _address + "/", _address);
    };

    return Api;

  })(Entity);

  s = angular.module("rainbowPatchApi", []);

  s.factory("Api", function() {
    return Api;
  });

}).call(this);
