// Generated by CoffeeScript 1.6.3
(function() {
  var methods, options, s;

  s = angular.module("rainbowServices");

  methods = {
    "list": {
      method: "GET",
      isArray: false
    },
    "query": {
      method: "GET",
      isArray: false
    }
  };

  options = {
    stripTrailingSlashes: false
  };

  s.factory("StoragePool", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/storage-pool/:storage_pool", port_replace, methods, options);
  });

  s.factory("StoragePoolVolume", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/storage-pool/:storage_pool/volume/:volume", port_replace, methods, options);
  });

  s.factory("StoragePoolDisk", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/storage-pool/:storage_pool/disk/:disk", port_replace, methods, options);
  });

  s.factory("Image", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/image/:image", port_replace, methods, options);
  });

  s.factory("ImageVolume", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/image/:image/volume/:volume", port_replace, methods, options);
  });

  s.factory("Switch", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/switch/:switch", port_replace, methods, options);
  });

  s.factory("SwitchVnic", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/switch/:switch/vnic/:vnic", port_replace, methods, options);
  });

  s.factory("SwitchNetwork", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/switch/:switch/network/:network", port_replace, methods, options);
  });

  s.factory("SwitchNetworkRoute", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/switch/:switch/network/:network/route/:route", port_replace, methods, options);
  });

  s.factory("SwitchNetworkAddress", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/switch/:switch/network/:network/address/:address", port_replace, methods, options);
  });

  s.factory("CpuProfile", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/cpu-profile/:cpu_profile", port_replace, methods, options);
  });

  s.factory("Host", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/host/:host", port_replace, methods, options);
  });

  s.factory("HostStoragePool", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/host/:host/storage-pool/:storage_pool", port_replace, methods, options);
  });

  s.factory("HostInstance", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/host/:host/instance/:instance", port_replace, methods, options);
  });

  s.factory("HostNic", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/host/:host/nic/:nic", port_replace, methods, options);
  });

  s.factory("HostImage", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/host/:host/image/:image", port_replace, methods, options);
  });

  s.factory("HostVolume", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/host/:host/volume/:volume", port_replace, methods, options);
  });

  s.factory("HostCpuProfile", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/host/:host/cpu-profile/:cpu_profile", port_replace, methods, options);
  });

  s.factory("HostDisk", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/host/:host/disk/:disk", port_replace, methods, options);
  });

  s.factory("HostEvent", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/host/:host/event/:event", port_replace, methods, options);
  });

  s.factory("HostBond", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/host/:host/bond/:bond", port_replace, methods, options);
  });

  s.factory("HostBondNic", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/host/:host/bond/:bond/nic/:nic", port_replace, methods, options);
  });

  s.factory("HostBondRole", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/host/:host/bond/:bond/role/:role", port_replace, methods, options);
  });

  s.factory("User", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/user/:user", port_replace, methods, options);
  });

  s.factory("UserMember", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/user/:user/member/:member", port_replace, methods, options);
  });

  s.factory("Disk", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/disk/:disk", port_replace, methods, options);
  });

  s.factory("Config", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/config/:config", port_replace, methods, options);
  });

  s.factory("Event", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/event/:event", port_replace, methods, options);
  });

  s.factory("Tenant", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant", port_replace, methods, options);
  });

  s.factory("TenantMember", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/member/:member", port_replace, methods, options);
  });

  s.factory("TenantAffinityGroup", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/affinity-group/:affinity_group", port_replace, methods, options);
  });

  s.factory("TenantAffinityGroupInstance", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/affinity-group/:affinity_group/instance/:instance", port_replace, methods, options);
  });

  s.factory("TenantImage", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/image/:image", port_replace, methods, options);
  });

  s.factory("TenantImageVolume", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/image/:image/volume/:volume", port_replace, methods, options);
  });

  s.factory("TenantQuota", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/quota/:quota", port_replace, methods, options);
  });

  s.factory("TenantVolume", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/volume/:volume", port_replace, methods, options);
  });

  s.factory("TenantVolumeVdisk", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/volume/:volume/vdisk/:vdisk", port_replace, methods, options);
  });

  s.factory("TenantInstance", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/instance/:instance", port_replace, methods, options);
  });

  s.factory("TenantInstanceVdisk", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/instance/:instance/vdisk/:vdisk", port_replace, methods, options);
  });

  s.factory("TenantInstanceAffinityGroup", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/instance/:instance/affinity-group/:affinity_group", port_replace, methods, options);
  });

  s.factory("TenantInstanceVnic", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/instance/:instance/vnic/:vnic", port_replace, methods, options);
  });

  s.factory("TenantInstanceVnicAddress", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/instance/:instance/vnic/:vnic/address/:address", port_replace, methods, options);
  });

  s.factory("TenantInstanceEvent", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/instance/:instance/event/:event", port_replace, methods, options);
  });

  s.factory("TenantSwitch", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/switch/:switch", port_replace, methods, options);
  });

  s.factory("TenantSwitchVnic", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/switch/:switch/vnic/:vnic", port_replace, methods, options);
  });

  s.factory("TenantSwitchNetwork", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/switch/:switch/network/:network", port_replace, methods, options);
  });

  s.factory("TenantSwitchNetworkRoute", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/switch/:switch/network/:network/route/:route", port_replace, methods, options);
  });

  s.factory("TenantSwitchNetworkAddress", function($resource, WEB_URL, WEB_PORT, API_SUFFIX) {
    var port_replace;
    port_replace = {};
    port_replace[WEB_PORT] = ":" + WEB_PORT;
    return $resource("" + WEB_URL + API_SUFFIX + "/tenant/:tenant/switch/:switch/network/:network/address/:address", port_replace, methods, options);
  });

}).call(this);
