// Generated by CoffeeScript 1.6.3
(function() {
  var ImageListCtrl, module;

  module = angular.module('tenant-image', []);

  module.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/:tenant/image', {
        templateUrl: 'tenant/image/image-list.tpl.html',
        controller: 'ImageListCtrl'
      });
    }
  ]);

  module.controller('ImageListCtrl', ImageListCtrl = (function() {
    ImageListCtrl.inject = ['$scope', '$routeParams', 'TenantImage'];

    function ImageListCtrl($scope, $routeParams, TenantImage) {
      $scope.images = TenantImage.get({
        'tenant': $routeParams.tenant
      });
    }

    return ImageListCtrl;

  })());

}).call(this);
