// Generated by CoffeeScript 1.7.1
(function() {
  var ImageDetailCtrl, ImageListCtrl, module,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  module = angular.module('tenantImage', ['rainbowServices']);

  module.config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/:tenant/image', {
        templateUrl: 'tenant/image/image-list.tpl.html',
        controller: 'ImageListCtrl'
      });
      return $routeProvider.when('/:tenant/image/:image', {
        templateUrl: 'tenant/image/image-detail.tpl.html',
        controller: 'ImageDetailCtrl'
      });
    }
  ]);

  module.controller('ImageListCtrl', ImageListCtrl = (function() {
    ImageListCtrl.inject = ['$scope', '$rootScope', '$routeParams', 'TenantImage', 'StoragePool', 'TenantVolume', 'dataContainer', '$modal'];

    function ImageListCtrl($scope, $rootScope, $routeParams, TenantImage, StoragePool, TenantVolume, dataContainer, $modal) {
      TenantImage.list({
        'tenant': $routeParams.tenant
      }).$promise.then(function(ImageList) {
        $scope.images = ImageList;
        return dataContainer.registerEntity('image', $scope.images);
      });
      StoragePool.list().$promise.then(function(StoragePoolList) {
        $scope.storagepools = StoragePoolList;
        return dataContainer.registerEntity('storage_pool', $scope.storagepools);
      });
      $scope.filterStatus = function(actual, expected) {
        expected = expected.toLowerCase();
        if ((actual != null) && 'initializing'.search(expected) > -1) {
          return true;
        }
        if ((actual == null) && 'ready'.search(expected) > -1) {
          return true;
        }
        return false;
      };
      $scope.imageModal = $modal({
        scope: $scope,
        template: 'tenant/image/image-modal.tpl.html',
        show: false
      });
      $scope.open = function() {
        $scope.image = {
          'storagepools': {}
        };
        return $scope.imageModal.show();
      };
      $scope.close = function() {
        $scope.imageModal.hide();
        return false;
      };
      $scope.createImage = function() {
        var newImage;
        newImage = new TenantImage();
        newImage.desired = {
          'name': $scope.image.name,
          'type': $scope.image.type,
          'description': $scope.image.description,
          'source_uri': $scope.image.source_uri
        };
        return newImage.$save({
          'tenant': $routeParams.tenant
        }, function(response) {
          var newVolume, storagepool, _results;
          _results = [];
          for (storagepool in $scope.image.storagepools) {
            if ($scope.image.storagepools[storagepool]) {
              newVolume = new TenantVolume();
              newVolume.desired = {
                'name': 'Image - "' + $scope.image.name + '"',
                'state': 'present',
                'size': $scope.image.size,
                'storage_pool': storagepool,
                'image': response.uuids.POST
              };
              _results.push(newVolume.$save({
                'tenant': $routeParams.tenant
              }, function(response) {
                return $scope.close();
              }));
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        });
      };
      $scope.deleteSelected = function(items) {
        var item, params, patch, _i, _len;
        patch = [];
        params = {
          'tenant': $routeParams.tenant
        };
        for (_i = 0, _len = items.length; _i < _len; _i++) {
          item = items[_i];
          patch.push({
            'op': 'remove',
            'path': '/' + item
          });
        }
        return TenantImage.patch(params, patch);
      };
    }

    return ImageListCtrl;

  })());

  module.controller('ImageDetailCtrl', ImageDetailCtrl = (function() {
    ImageDetailCtrl.inject = ['$scope', '$rootScope', '$routeParams', 'TenantImage', 'TenantImageVolume', 'TenantVolume', 'StoragePool', 'dataContainer', '$modal'];

    function ImageDetailCtrl($scope, $routeParams, TenantImage, TenantImageVolume, TenantVolume, StoragePool, dataContainer, $modal, $route) {
      var criteria;
      criteria = {
        'tenant': $routeParams.tenant,
        'image': $routeParams.image
      };
      TenantImage.get(criteria).$promise.then(function(image) {
        $scope.image = image;
        return dataContainer.registerResource($scope.image, $scope.image.desired.uuid);
      });
      TenantVolume.list({
        'tenant': $routeParams.tenant
      }).$promise.then(function(volumes) {
        $scope.volumes = volumes;
        return dataContainer.registerEntity('volume', $scope.volumes);
      });
      $scope.storagepools = {};
      $scope.imageEditModal = $modal({
        scope: $scope,
        template: 'tenant/image/image-edit-modal.tpl.html',
        show: false
      });
      $scope.volumeListModal = $modal({
        scope: $scope,
        template: 'tenant/image/volume-list-modal.tpl.html',
        show: false
      });
      StoragePool.list().$promise.then(function(StoragePoolList) {
        $scope.splist = StoragePoolList;
        dataContainer.registerEntity('storagepool', $scope.storagepools);
        return TenantImageVolume.list(criteria).$promise.then(function(TenantImageList) {
          $scope.backVolumes = TenantImageList;
          return dataContainer.registerEntity('volume', $scope.backVolumes);
        });
      });
      $scope.$watch('backVolumes', function(value) {
        console.log('Refreshing volumes');
        console.log($scope.backVolumes);
        return $scope.refreshVolumes();
      }, true);
      $scope.refreshVolumes = function() {
        var key, storagepool, volume, _i, _j, _len, _len1, _ref, _ref1, _results;
        if (!$scope.splist) {
          return;
        }
        $scope.storagepools = {};
        _ref = $scope.splist;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          storagepool = _ref[_i];
          $scope.storagepools[storagepool.desired.uuid] = storagepool;
        }
        for (key in $scope.storagepools) {
          $scope.storagepools[key].volumes = [];
          $scope.storagepools[key].used = false;
          $scope.storagepools[key].used_space = 0;
        }
        _ref1 = $scope.backVolumes;
        _results = [];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          volume = _ref1[_j];
          $scope.storagepools[volume.desired.storage_pool].used = true;
          if (__indexOf.call($scope.storagepools[volume.desired.storage_pool].volumes, volume) < 0) {
            $scope.storagepools[volume.desired.storage_pool].volumes.push(volume);
            $scope.storagepools[volume.desired.storage_pool].used_space += volume.desired.size;
          }
          $scope.imageSize = volume.desired.size;
          _results.push($scope.image.size = $scope.imageSize);
        }
        return _results;
      };
      $scope.open = function() {
        $scope.volumes = $scope.volumes.filter(function(item) {
          if (!(item.desired.image || item.desired.image === $routeParams.image)) {
            return item;
          }
        });
        return $scope.imageEditModal.show();
      };
      $scope.close = function(reload) {
        if (reload == null) {
          reload = true;
        }
        $scope.imageEditModal.hide();
        if (reload) {
          $route.reload();
        }
        return false;
      };
      $scope.volumeListOpen = function() {
        return $scope.volumeListModal.show();
      };
      $scope.volumeListClose = function() {
        $scope.volumeListModal.hide();
        return false;
      };
      $scope.allocate = function(storagepool, size) {
        var desired, newVolume;
        desired = {
          'name': 'Image - "' + $scope.image.desired.name + '"',
          'state': 'present',
          'size': size,
          'storage_pool': storagepool.desired.uuid,
          'image': $scope.image.desired.uuid
        };
        newVolume = new TenantVolume();
        newVolume.desired = desired;
        return newVolume.$save({
          'tenant': $routeParams.tenant
        });
      };
      $scope.deallocate = function(storagepool) {
        var params, volume, _i, _len, _ref, _results;
        _ref = storagepool.volumes;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          volume = _ref[_i];
          params = {
            'tenant': $routeParams.tenant,
            'volume': volume.desired.uuid
          };
          _results.push(TenantVolume["delete"](params));
        }
        return _results;
      };
      $scope.unlink = function(volume) {
        var params, patch;
        patch = JSON.stringify([
          {
            'op': 'remove',
            'path': '/desired/image'
          }
        ]);
        params = {
          'tenant': $routeParams.tenant,
          'volume': volume.desired.uuid
        };
        return TenantVolume.patch(params, patch, function() {
          return $scope.backVolumes.splice($scope.backVolumes.indexOf(volume), 1);
        });
      };
      $scope.editImage = function() {
        var params, patch;
        patch = JSON.stringify([
          {
            'op': 'x-merge',
            'path': '/desired',
            'value': {
              'name': $scope.image.desired.name,
              'description': $scope.image.desired.description,
              'type': $scope.image.desired.type,
              'source_uri': $scope.image.desired.source_uri
            }
          }
        ]);
        params = {
          'tenant': $routeParams.tenant,
          'image': $routeParams.image
        };
        return TenantImage.patch(params, patch, function() {
          return $scope.close(false);
        });
      };
    }

    return ImageDetailCtrl;

  })());

}).call(this);
