// Generated by CoffeeScript 1.7.1
(function() {
  var AffinityGroupDetailCtrl, AffinityGroupListCtrl, module;

  module = angular.module('tenant-affinity-group', ['rainbowServices']);

  module.config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/:tenant/affinity-group', {
        templateUrl: 'tenant/affinity-group/affinity-group-list.tpl.html',
        controller: 'AffinityGroupListCtrl'
      });
      return $routeProvider.when('/:tenant/affinity-group/:affinity_group', {
        templateUrl: 'tenant/affinity-group/affinity-group-detail.tpl.html',
        controller: 'AffinityGroupDetailCtrl'
      });
    }
  ]);

  module.controller('AffinityGroupListCtrl', AffinityGroupListCtrl = (function() {
    AffinityGroupListCtrl.inject = ['$scope', '$rootScope', '$routeParams', 'TenantAffinityGroup', 'dataContainer'];

    function AffinityGroupListCtrl($scope, $rootScope, $routeParams, TenantAffinityGroup, dataContainer) {
      TenantAffinityGroup.list({
        'tenant': $routeParams.tenant
      }).$promise.then(function(affinityGroupList) {
        $scope.affinityGroups = affinityGroupList;
        return dataContainer.registerEntity('affinityGroup', $scope.affinityGroups);
      });
      $scope.opts = {
        backdropFade: true,
        dialogFade: true
      };
      $scope.open = function(affinityGroup) {
        $scope.affinityGroupModal = true;
        if (typeof affinityGroup !== 'undefined') {
          return $scope.affinityGroup = affinityGroup.desired;
        } else {
          return $scope.affinityGroup = null;
        }
      };
      $scope.close = function() {
        $scope.closeMsg = 'I was closed at: ' + new Date();
        $scope.affinityGroupModal = false;
        return false;
      };
      $scope.createAffinityGroup = function() {
        var newAffinityGroup;
        newAffinityGroup = new TenantAffinityGroup();
        newAffinityGroup.desired = {
          'name': $scope.affinityGroup.name,
          'type': $scope.affinityGroup.type
        };
        return newAffinityGroup.$save({
          'tenant': $routeParams.tenant
        }, function(response) {
          return $scope.affinityGroups.push({
            'desired': {
              'uuid': response.uuids.POST,
              'name': $scope.affinityGroup.name
            }
          });
        });
      };
      $scope.modifyAffinityGroup = function() {
        if (typeof $scope.affinityGroup.uuid === 'undefined') {
          $scope.createAffinityGroup();
        } else {
          $scope.editAffinityGroup();
        }
        return $scope.close();
      };
      $scope.editAffinityGroup = function() {
        var params, patch;
        patch = JSON.stringify([
          {
            'op': 'x-merge',
            'path': '/desired',
            'value': {
              'name': $scope.affinityGroup.name,
              'type': $scope.affinityGroup.type
            }
          }
        ]);
        params = {
          'tenant': $routeParams.tenant,
          'affinity_group': $scope.affinityGroup.uuid
        };
        return TenantAffinityGroup.patch(params, patch, function() {
          return $scope.message("Affinity group modified", 'success');
        });
      };
      $scope.deleteAffinityGroup = function(affinityGroup, index) {
        var params, position;
        position = $scope.affinityGroups.indexOf(affinityGroup);
        params = {
          'tenant': $routeParams.tenant,
          'affinity_group': affinityGroup.desired.uuid
        };
        return TenantAffinityGroup["delete"](params, function() {
          $scope.affinityGroups.splice(position, 1);
          return $scope.message("Affinity group deleted", 'success');
        });
      };
    }

    return AffinityGroupListCtrl;

  })());

  module.controller('AffinityGroupDetailCtrl', AffinityGroupDetailCtrl = (function() {
    AffinityGroupDetailCtrl.inject = ['$scope', '$rootScope', '$routeParams', 'TenantAffinityGroup', 'dataContainer'];

    function AffinityGroupDetailCtrl($scope, $routeParams, TenantAffinityGroup, TenantAffinityGroupInstanceJoin) {
      $scope.affinityGroup = TenantAffinityGroup.get({
        'tenant': $routeParams.tenant,
        'affinity_group': $routeParams.affinity_group
      });
      $scope.instances = TenantAffinityGroupInstanceJoin.list({
        'tenant': $routeParams.tenant,
        'affinity_group': $routeParams.affinity_group
      });
    }

    return AffinityGroupDetailCtrl;

  })());

}).call(this);
